/*
 * ADOBE CONFIDENTIAL
 *
 * Copyright (c) 2014 Adobe Systems Incorporated. All rights reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe Systems Incorporated and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Adobe Systems Incorporated and its
 * suppliers and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe Systems Incorporated.
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

/*
 *
 * Do *NOT* translate the string keys on the left of the colon.  These string
 *    keys *MUST* match the string values used in the JS.
 *
 * This file contains the translate() table copied from the last pull of Extract CCW.
 * The English language `root` strings are embedded directly in the JS.  However,
 *   the localized strings for this language will be provided in the table below.
 *
 */

define({
    " {0} is not an email address": " {0} n’est pas une adresse électronique.",
    "&copy; 2014 Adobe Systems Incorporated. All Rights Reserved.": "&copy; 2014 Adobe Systems Incorporated. All Rights Reserved.",
    "&copy; 2014 Adobe Systems Software Ireland Ltd. All Rights Reserved.": "&copy; 2014 Adobe Systems Software Ireland Ltd. All Rights Reserved.",
    "(updated)": "(mise à jour)",
    "1": "1",
    "1 {0} file is being downloaded.": "1 fichier {0} est en cours de téléchargement.",
    "1. Upload your PSD to Creative Cloud Files.": "1. Téléchargez vos fichiers PSD dans Creative Cloud Files.",
    "2": "2",
    "2. Share your PSD with others.": "2. Partagez vos PSD avec d’autres.",
    "256 colors. Lowest file size. Alpha transparency to be retained if present in element.": "256 couleurs. Taille de fichier minimale. Transparence Alpha à conserver en cas de présence dans l’élément.",
    "3": "3",
    "3. Enable others to extract CSS, colors, fonts and more.": "3. Autorisez les autres utilisateurs à extraire le code CSS, les couleurs, les polices, etc.",
    "4": "4",
    "5": "5",
    "</p>": "</p>",
    "<span>1.</span> Create your site with the app that\\'s right for you": "<span>1.</span> Créez votre site avec l’application qui vous convient le mieux",
    "<span>2.</span> Push your site live with Adobe Web Hosting": "<span>2.</span> Donnez vie à votre site grâce à Adobe Web Hosting.",
    "A file with that name already exists. Please rename your file and try again.": "Il existe déjà un fichier portant ce nom. Veuillez renommer le fichier et réessayer.",
    "A folder with that name already exists in this folder.": "Il existe déjà un dossier portant le même nom dans ce dossier.",
    "A valid email address is required.": "Adresse électronique valide requise.",
    "ALT +/- to zoom in and out": "Zoom avant et arrière : ALT +/-",
    "Accept": "Accepter",
    "Accepted 1 invitation. Added {0} to Creative Cloud.": "1 invitation acceptée. {0} a été ajouté à Creative Cloud.",
    "Access": "Accès",
    "Action": "Script d'action",
    "Actions": "Actions",
    "Activity": "Activité",
    "Add": "Ajouter",
    "Add Comment": "Ajouter un commentaire",
    "Add Optional Description": "Ajouter une description (facultatif)",
    "Add Required Title": "Ajouter un titre (obligatoire)",
    "Add comment": "Ajouter un commentaire",
    "Add new licenses for your team and invite new members. Don\\'t forget to assign a license to yourself if you\\'d like to use apps from Creative Cloud as well!": "Ajoutez de nouvelles licences à l’attention de votre équipe et invitez de nouveaux membres. N’oubliez pas de vous attribuer une licence à vous-même si vous voulez, vous aussi, profiter des applications Creative Cloud !",
    "Added file \\'{0}\\'.": "Fichier « {0} » ajouté.",
    "Added folder \\'{0}\\'.": "Dossier « {0} » ajouté.",
    "Added {0} items.": "{0} éléments ajoutés.",
    "Adding...": "Ajout en cours...",
    "Adobe Add-ons": "Adobe Add-ons",
    "Adobe Add-ons is currently unavailable.": "Adobe Add-ons n’est pas disponible actuellement.",
    "Adobe Brushes": "Pinceaux Adobe",
    "Adobe Creative Cloud": "Adobe Creative Cloud",
    "Adobe Creative Cloud requires JavaScript in order to load properly. Please enable JavaScript in your browser and reload the page.": "Pour pouvoir se charger correctement, Adobe Creative Cloud requiert JavaScript. Veuillez activer JavaScript dans votre navigateur et recharger la page.",
    "Adobe Creative Cloud requires cookies to be enabled in order to load properly. Please enable cookies in your browser and reload the page.": "Les cookies doivent être activés pour que le chargement d’Adobe Creative Cloud s’effectue correctement. Activez les cookies dans votre navigateur et rechargez la page.",
    "Adobe Sketch": "Adobe Sketch",
    "Adobe TV Videos": "Vidéos Adobe TV",
    "Adobe Web Hosting lets you easily publish desktop and mobile-friendly websites created using Adobe Muse or Dreamweaver. Hosting for five sites is included as part of your Creative Cloud membership.": "Adobe Web Hosting vous permet de publier facilement des sites web optimisés pour ordinateurs de bureau et appareils mobiles que vous avez créés dans Adobe Muse ou Dreamweaver. Vous pouvez héberger jusqu’à cinq sites web dans le cadre de votre abonnement Creative Cloud.",
    "Adobe&nbsp;Creative&nbsp;Cloud Maintenance": "Maintenance d’Adobe&nbsp;Creative&nbsp;Cloud",
    "Adobe&reg;&nbsp;Creative&nbsp;Cloud&#153; requires cookies to be enabled in order to load properly.": "Les cookies doivent être activés pour qu’Adobe&reg;&nbsp;Creative&nbsp;Cloud&#153; se charge correctement.",
    "Advanced Options": "Options avancées",
    "After building and testing your app, your final step is to submit it to the Apple App Store. This video covers the basics involved. For detailed instructions, refer to the &quot;Submit to the App Store&quot; section of the Step-by-Step Guide.": "Après avoir développé et testé votre application, la dernière étape consiste à l’envoyer à l’App Store d’Apple. Cette vidéo présente les étapes de base que cela implique. Pour obtenir des instructions détaillées, reportez-vous à la section « Envoi vers l’App Store » du Guide détaillé.",
    "After extracting assets, find them in the Assets tab where they can be downloaded locally.": "Une fois extraits, les actifs se trouvent dans l’onglet Actifs, d’où ils peuvent être téléchargés en local.",
    "All": "Tout",
    "All Activity": "Toute l’activité",
    "All Categories": "Toutes les catégories",
    "All settings have been cleared.": "Tous les paramètres ont été effacés.",
    "All you need is an Adobe ID": "Vous n’avez besoin que d’un ID Adobe.",
    "Allow File Download": "Autoriser le téléchargement de fichiers",
    "Allow use of {0}": "Permettre l’utilisation de {0}",
    "Allows extraction of pixel-level color values.": "Permet l’extraction de valeurs de couleur au pixel près.",
    "Already have an Adobe ID?": "Vous possédez déjà un ID Adobe ?",
    "Already have it installed? Relaunch the app and go to the Files panel to start syncing.": "Si c’est déjà fait, relancez simplement l’application et ouvrez le panneau Fichiers pour commencer la synchronisation.",
    "An email with instructions for resetting your password has already been sent. Please check your email, or try again in a few minutes.": "Les instructions à suivre pour réinitialiser votre mot de passe vous a été envoyées par courrier électronique. Consultez votre messagerie ou réessayez dans quelques minutes.",
    "An error occured, please try again.": "Une erreur est survenue. Veuillez réessayer.",
    "An error occurred, please refresh your browser and try again.": "Une erreur s’est produite, veuillez actualiser votre navigateur et réessayer.",
    "An error occurred, please try again.": "Une erreur s’est produite, veuillez réessayer.",
    "An item with that name already exists in this folder.": "Un élément portant le même nom existe déjà dans ce dossier.",
    "An unexpected error occurred. Please try again later.": "Une erreur inattendue s’est produite. Veuillez réessayer ultérieurement.",
    "Application settings are synced between many of your favorite desktop applications and Creative Cloud, allowing you to work consistently from any machine. To begin syncing, you will need to open your desktop application and click {0}Sync Settings Now{1}.": "Les paramètres d’application sont synchronisés entre vos applications de bureau préférées et Creative Cloud. Vous pouvez ainsi travailler de manière homogène sur n’importe quel ordinateur. Pour lancer la synchronisation, ouvrez l’application concernée et cliquez sur {0}Synchroniser les paramètres maintenant{1}.",
    "Application settings are temporarily unavailable. Please try again later.": "Les paramètres d’application sont temporairement indisponibles. Veuillez réessayer ultérieurement.",
    "Apply": "Appliquer",
    "Approximation due to font substitution": "Approximation causée par une substitution de police",
    "April": "Avril",
    "Archive": "Archiver",
    "Archive {0} item(s)?": "Archiver {0} élément(s) ?",
    "Ascending": "Ascendant",
    "Ask experts in the {0}forums{1}.": "Demandez l’avis d’experts sur nos {0}forums{1}.",
    "Assets": "Actifs",
    "August": "Août",
    "B": "octets",
    "Base font size": "Taille de la police de base",
    "Browse files within {0}": "Parcourir les fichiers dans {0}",
    "Browse for the program you need and install it": "Recherchez le programme dont vous avez besoin et installez-le.",
    "Browse for the program you need and {0}install it directly from your Creative Cloud desktop application{1}": "Recherchez le programme dont vous avez besoin et {0}installez-le directement depuis votre application de bureau Creative Cloud{1}.",
    "Brushes": "Formes",
    "Business Catalyst Site Builder": "Business Catalyst Site Builder",
    "By Date": "Par date",
    "By Name": "Par nom",
    "By Size": "Par taille",
    "By Type": "Par type",
    "By signing up for the Early Access program, you agree to Adobe\\'s {0}Terms of Use{1} and {2}Privacy Policy{3}.": "En vous inscrivant au programme d’accès en avant-première, vous acceptez les [[0]conditions d’utilisation{1} et la {2}politique de confidentialité{3} d’Adobe.",
    "CSS copied to clipboard": "Code CSS copié dans le Presse-papiers",
    "Cancel": "Annuler",
    "Category": "Catégorie",
    "Changing the file extension from {0} to {1}.": "Modification de l’extension de fichier de {0} à {1}.",
    "Choose a file format to download": "Sélectionner un format de fichier pour le téléchargement",
    "Choose a folder": "Choisir un dossier",
    "Clear All": "Effacer tout",
    "Clear Settings": "Effacer les paramètres",
    "Clear/Exit": "Effacer/Quitter",
    "Click Extract to do all this in your browser:": "Cliquez sur Extract pour réaliser les opérations suivantes dans votre navigateur :",
    "Click to copy": "Cliquer pour copier",
    "Click to download": "Cliquez pour télécharger",
    "Close": "Fermer",
    "Collaborate": "Collaborer",
    "Collaborate with {0}": "Collaborer avec {0}",
    "Collaborators": "Collaborateurs",
    "Collaborators {0}Preview{1}": "{0}Aperçu{1} des collaborateurs",
    "Color Picker": "Sélecteur de couleurs",
    "Colors": "Couleurs",
    "Combine feature set(s)": "Combiner les ensembles de fonctionnalités",
    "Comment &amp; version history helps you track changes - and gives you peace of mind.": "L’historique des commentaires et des versions vous permet de suivre les modifications effectuées et de travailler l’esprit tranquille.",
    "Comment required": "Commentaire requis",
    "Comments": "Commentaires",
    "Contact Behance Help": "Contacter l’aide de Behance",
    "Converting Image...": "Conversion de l’image...",
    "Cookies": "Cookies",
    "Copied": "Copié",
    "Copy": "Copier",
    "Copy All": "Copier tout",
    "Copy CSS": "Copier le code CSS",
    "Copy Text": "Copier le texte",
    "Copy text and CSS": "Copier le texte et le code CSS",
    "Copyright": "Copyright",
    "Create Folder": "Créer un dossier",
    "Create Public Link": "Créer un lien public",
    "Create a new Adobe ID": "Créer un nouvel ID Adobe",
    "Create an Adobe ID": "Créer un ID Adobe",
    "Created new folder \\'{0}\\'": "Nouveau dossier créé \\'{0}\\'",
    "Creative Cloud": "Creative Cloud",
    "Creative Cloud Assets": "Actifs Creative Cloud",
    "Creative Cloud Connection": "Creative Cloud Connection",
    "Creative Cloud Files is currently unavailable.": "Creative Cloud Files est actuellement indisponible.",
    "Creative Cloud has experienced an unexpected Sign In failure. Please try again later.": "Creative Cloud a rencontré un problème de connexion inattendu. Veuillez réessayer ultérieurement.",
    "Creative Cloud is currently experiencing issues with a small number of file types. Previews and download conversions will be delayed for these files. We are working to resolve these issues as quickly as possible. Thank you for your patience.": "Creative Cloud rencontre actuellement des problèmes avec quelques types de fichier. La génération des aperçus et les conversions de téléchargement seront retardées pour ces fichiers. Nous travaillons actuellement sur ces problèmes afin de les résoudre au plus vite. Merci de votre compréhension.",
    "Creative Cloud is currently unavailable. We will be back online as soon as possible. Thank you for your patience!": "Creative Cloud n’est pas disponible pour le moment. La connexion sera rétablie dès que possible. Nous vous remercions pour votre patience.",
    "Creative Cloud is currently undergoing maintenance. Please check back later. Thank you for your patience.": "Creative Cloud est actuellement en maintenance. Veuillez réessayer ultérieurement. Nous vous remercions pour votre patience.",
    "Current Version": "Version actuelle",
    "December": "Décembre",
    "Declined 1 invitation.": "1 invitation refusée.",
    "Defamation": "Diffamation",
    "Delete Asset": "Supprimer l’actif",
    "Delete Comment": "Supprimer le commentaire",
    "Delete comment by {0}?": "Supprimer le commentaire de {0} ?",
    "Delete {0} items?": "Supprimer {0} éléments ?",
    "Delete {0}?": "Supprimer {0} ?",
    "Descending": "Descendant",
    "Description": "Description",
    "Design Libraries": "Bibliothèques de conception",
    "Desktop": "Bureau",
    "Desktop Sync Settings": "Synchronisation des paramètres de bureau",
    "Details": "Détails",
    "Did this work as expected?": "Cette opération s’est-elle déroulée comme prévu ?",
    "Digital Publishing Gallery": "Galerie Digital Publishing",
    "Digital Publishing Suite Help": "Aide Digital Publishing Suite",
    "Digital Publishing Support Forums": "Forums d’aide Digital Publishing",
    "Direct Select": "Sélection directe",
    "Done": "Terminé",
    "Download": "Télécharger",
    "Download Center": "Centre de téléchargement",
    "Download the Creative Cloud app": "Télécharger l’application Creative Cloud",
    "Download the Step-by-Step Guide to Publishing iPad Apps with DPS, Single Edition": "Télécharger le guide détaillé pour la publication d’applications pour iPad avec DPS, édition Single",
    "Download the {0}Creative Cloud desktop application{1} and install it on your machine (or ask your IT administrator to install it for you)": "Téléchargez l’{0}application de bureau Creative Cloud{1} et installez-la sur votre ordinateur (ou demandez à votre responsable informatique de s’en charger).",
    "Download the {0}Creative Cloud desktop application{1}, which will help you manage all your favorite Adobe applications directly from your desktop": "Téléchargez l’{0}application de bureau Creative Cloud{1}, grâce à laquelle vous pourrez gérer toutes vos applications Adobe favorites directement depuis le bureau.",
    "Downloaded": "Téléchargés",
    "Drag Files Here": "Faites glisser les fichiers ici",
    "Drag and drop your files here, or use the {0}file chooser{1}{2}.": "Faites glisser les fichiers ici ou utilisez le {0}sélecteur de fichier{1}{2}.",
    "Easily manage your Creative Cloud licenses by clicking on the Get Started button below.": "Gérez facilement vos licences Creative Cloud en cliquant sur le bouton Démarrer ci-dessous.",
    "Email": "Courrier électronique",
    "Email address": "Adresse électronique",
    "Empty Archive": "Vider l’archive",
    "Emptying Archive": "Vidage de l’archive",
    "Emptying archive...": "Vidage de l’archive...",
    "Enter email address": "Indiquer une adresse e-mail",
    "Enter the email address you use for your Adobe ID and we will send you instructions.": "Saisissez l'adresse électronique que vous utilisez pour votre ID Adobe et nous vous enverrons des instructions.",
    "Error extracting asset.": "Erreur lors de l’extraction de l’actif.",
    "Error extracting asset. You've possibly exceeded your storage limit.": "Erreur lors de l’extraction de l’actif. Il est possible que vous ayez dépassé votre limite de stockage.",
    "Error retrieving derived assets ({0})": "Erreur lors de la récupération des actifs dérivés ({0})",
    "Extract": "Extract",
    "Extract FAQ": "FAQ concernant Extract",
    "Extract Forums": "Forums traitant d’Extract",
    "Extract Help": "Aide concernant Extract",
    "Extract asset": "Extraire l’actif",
    "Extract asset at specified scale factor": "Extraire l’actif selon le facteur d’échelle spécifié",
    "Extract helps web designers and developers turn PSD comps into code-based designs &mdash; in the browser.": "Extract permet aux designers et aux développeurs de transformer facilement des compositions PSD en conceptions codées, et ce, directement dans le navigateur.",
    "Extract requires a minimum width of 800 pixels": "Extract nécessite une largeur minimale de 800 pixels.",
    "Extracted Assets": "Actifs extraits",
    "Extracting asset. Look for it in the Assets tab.": "Extraction de l’actif en cours. Retrouvez-le dans l’onglet Actifs.",
    "Eyedropper Tool": "Outil Pipette",
    "FIT": "AJUSTER",
    "Failed to load plugin: {0}": "Impossible de charger le module externe {0}",
    "Featured": "Recommandés",
    "February": "Février",
    "File Sync is Now Available": "La synchronisation de fichiers est maintenant disponible",
    "File and font sync is now activated for Creative Cloud members with annual or monthly subscription plans.": "La fonctionnalité Synchronisation de fichiers et de polices est désormais activée pour les membres Creative Cloud titulaires d’un abonnement mensuel ou annuel.",
    "File information": "Informations sur les fichiers",
    "Files": "Fichiers",
    "Files and folders you own will be archived and you will be removed from collaboration on folders owned by others.": "Les fichiers et dossiers qui vous appartiennent seront archivés et vous ne ferez plus partie de la liste des collaborateurs pour les dossiers appartenant à d’autres utilisateurs.",
    "Find answers to common questions {0}here{1}.": "Trouvez les réponses aux questions les plus fréquentes {0}ici{1}.",
    "Find font on typekit.com": "Trouver une police sur typekit.com",
    "Find the {0} and open it to start installation": "Recherchez le fichier {0} et ouvrez-le pour commencer l’installation.",
    "First User Experience Guide (i)": "Guide destiné aux utilisateurs débutants (i)",
    "First, the Adobe Application Manager will download": "Adobe Application Manager va tout d’abord être téléchargé.",
    "Folder names must not be blank.": "Les noms des dossiers ne doivent pas être vides.",
    "Follow the instructions to create a new password.": "Suivez les instructions pour créer un nouveau mot de passe.",
    "Fonts": "Polices",
    "For Placement": "Pour positionnement",
    "Forgot Your Password?": "Mot de passe oublié ?",
    "Forgot password?": "Mot de passe oublié ?",
    "Format": "Format",
    "Full Creative Cloud Membership comes with hosting for up to 5 sites. View and manage these sites from the sidebar on the Creative Cloud home page.": "L’adhésion complète à Creative Cloud comprend l’hébergement de 5 sites maximum. Consultez et gérez ces sites depuis la barre latérale située sur la page d’accueil de Creative Cloud.",
    "GB": "Go",
    "Get Access to File and Font Sync": "Accéder à la fonctionnalité Synchronisation de fichiers et de polices",
    "Get Early Access to File Sync": "Accéder en avant-première à la synchronisation de fichiers",
    "Get Started": "Commencer",
    "Get color, gradient, and font info": "Obtenir des informations sur les couleurs, les dégradés et les polices",
    "Get started": "Commencer",
    "Get started on your website": "Premiers pas avec votre site web",
    "Getting started with Adobe Digital Publishing Suite, Single Edition": "Prise en main d’Adobe Digital Publishing Suite, édition Single",
    "Go to Comments to preview the PSD.": "Ouvrez la section Commentaires pour afficher un aperçu du PSD.",
    "Go to Details to preview the PSD.": "Ouvrez la section Détails pour afficher un aperçu du PSD.",
    "Go to your downloads folder": "Accédez à votre dossier de téléchargement.",
    "Gradients": "Dégradés",
    "Height": "Hauteur",
    "Help": "Aide",
    "Help is available in the {0}Creative Cloud forums{1}.": "Vous pouvez obtenir de l’aide sur les {0}forums Creative Cloud{1}.",
    "Here\\'s what\\'s next": "Voici ce qui vous attend",
    "Hi": "Bonjour",
    "Hide Folder Covers": "Masquage de la page de couverture des dossiers",
    "Home": "Accueil",
    "Hover over thumbnails in the Layers tab to see a preview for a layer or layer group.": "Passez la souris sur les miniatures de l’onglet Calques pour afficher l’aperçu d’un calque ou d’un groupe de calques.",
    "I don&#39;t know my Adobe ID": "Je ne connais pas mon ID Adobe.",
    "Icons": "Icônes",
    "If you feel that this Creative Cloud content violates the Adobe {0}Terms of Use{1}, you may report this content by filling out this quick form.": "Si vous estimez que ce contenu Creative Cloud enfreint les {0}Conditions d’utilisation{1} d’Adobe, vous pouvez effectuer un signalement en complétant ce formulaire.",
    "If you\\'d like, download Creative Cloud Packager to simplify the software installation process and quickly get your team members set up.": "Si vous le souhaitez, téléchargez Creative Cloud Packager pour simplifier le processus d’installation des logiciels et faire en sorte que les membres de votre équipe soient rapidement opérationnels.",
    "If you\\'re a free member and don\\'t yet have a subscription plan, you can sign up here to turn on file sync. We\\'ll add you to the waiting list, and send you an email once you have access.": "Si vous êtes membre à titre gratuit et ne possédez pas encore d’abonnement, vous pouvez vous inscrire ici pour activer la fonctionnalité de synchronisation de fichiers. Vous serez alors ajouté à notre liste d’attente et recevrez un e-mail dès que votre accès sera activé.",
    "Image": "Image",
    "Import": "Importation",
    "Import Files": "Importer des fichiers",
    "Info": "Infos",
    "Inline Style": "Style intégré",
    "Interested in trying our Additional Storage offering? Contact {0}Customer Support{1} to sign up for early access.": "Notre offre Stockage supplémentaire vous intéresse ? Contactez le {0}Service clientèle{1} pour vous inscrire et bénéficier d\\'un accès rapide.",
    "Invitation Not Found": "Invitation non trouvée",
    "Invite": "Inviter",
    "Invite not found.": "Invitation non trouvée.",
    "Invited": "Invité",
    "It lets you download every app available on Creative Cloud straight to your desktop.": "Vous pouvez télécharger toutes les applications disponibles dans Creative Cloud, directement sur votre poste de travail.",
    "It\\'s great to see you here with the rest of your team. Let\\'s get started so you can get down to business.": "Nous sommes ravis de vous compter parmi nous. Maintenant, passons aux choses sérieuses.",
    "It\\'s great to see you here. Let\\'s get started so you can get down to business.": "Nous sommes ravis de vous compter parmi nous. Maintenant, passons aux choses sérieuses.",
    "Item(s) Archived.": "Elément(s) archivé(s).",
    "JPG": "JPG",
    "January": "Janvier",
    "JavaScript Disabled!": "JavaScript est désactivé.",
    "Job queued...": "Tâche placée dans la file d’attente...",
    "July": "Juillet",
    "June": "Juin",
    "KB": "Ko",
    "Keep me signed in": "Maintenir la connexion",
    "Keyboard Shortcuts": "Raccourcis clavier",
    "Keyboard Shortcuts Guide (?)": "Guide des raccourcis clavier (?)",
    "Language:": "Langue :",
    "Last Document State": "Dernier état du document",
    "Launch Site Builder": "Démarrer Site Builder",
    "Launched Sites ({0})": "Sites lancés ({0})",
    "Layers": "Calques",
    "Learn": "Formation",
    "Learn More": "En savoir plus",
    "Learn More.": "En savoir plus.",
    "Leave Folder": "Quitter le dossier",
    "Leave folder": "Quitter le dossier",
    "Leave folders": "Quitter les dossiers",
    "Leave {0}": "Quitter {0}",
    "Libraries": "Bibliothèques",
    "List": "Liste",
    "Loading...": "Chargement en cours...",
    "Lossless format so better quality.": "Format sans perte, pour une meilleure qualité.",
    "MB": "Mo",
    "Made With": "Conçu avec",
    "Make Playable": "Autoriser la lecture",
    "Manage": "Gérer",
    "Manage Collaborators": "Gérer les collaborateurs",
    "March": "Mars",
    "Market": "Market",
    "Market Assets": "Actifs Market",
    "May": "Mai",
    "Measure between elements": "Mesurer la distance entre des éléments",
    "Min Sheets": "Nb minimum de feuilles",
    "Mobile": "Portable",
    "Mobile Assets": "Actifs mobiles",
    "Modified": "Modifié",
    "Mosaic": "Mosaïque",
    "Most Relevant": "Les plus pertinents",
    "Move": "Déplacer",
    "Move to '{0}'": "Déplacer vers {0}",
    "Move to folder": "Déplacer vers le dossier",
    "Move {0} items": "Déplacer {0} éléments",
    "Moved 1 item into \\'{0}\\'": "1 élément déplacé vers « {0} »",
    "Moved file \\'{0}\\' to the archive.": "Fichier \\'{0}\\' déplacé vers les archives.",
    "Moved folder \\'{0}\\' and all of its content to the archive.": "Dossier \\'{0}\\' déplacé vers les archives (avec son contenu).",
    "Moved {0} items into \\'{1}\\'": "{0} éléments déplacés vers « {1} »",
    "Moved {0} items to the archive.": "{0} éléments déplacés vers les archives.",
    "Moving \\'{0}\\'": "Déplacement de « {0} »",
    "Moving {0} items": "Déplacement de {0} éléments",
    "Moving...": "Déplacement en cours...",
    "Multi-Select": "Sélection multiple",
    "Multiple Revisions": "Plusieurs révisions",
    "Multiple files may not be used to replace. Please select a single file.": "Il est impossible d’utiliser plusieurs fichiers pour le remplacement. Veuillez sélectionner un fichier unique.",
    "My Assets": "Mes actifs",
    "My Websites": "Mes sites Web",
    "Name": "Nom",
    "Name required": "Nom requis",
    "Need an Adobe ID?": "Besoin d’un ID Adobe ?",
    "Next/Previous Sibling Layer": "Calque frère précédent/suivant",
    "No": "Non",
    "No launched sites": "Aucun site lancé",
    "No results": "Aucun résultat",
    "No temporary sites": "Aucun site temporaire",
    "Not your Adobe ID?": "Autre ID Adobe ?",
    "November": "Novembre",
    "Now that you\\'ve built your content, it\\'s time to build your app. This video introduces how to use DPS App Builder to generate your app. Refer to the &quot;Build the App with DPS App Builder&quot; section in the Step-by-Step Guide.": "Maintenant que votre contenu est au point, il est temps de développer votre application. Cette vidéo explique comment utiliser DPS App Builder pour générer votre propre application. Reportez-vous à la section « Création d’une application avec DPS App Builder » du Guide détaillé.",
    "OK": "OK",
    "October": "Octobre",
    "Offensive Content": "Contenu choquant",
    "Open the Creative Cloud app": "Ouvrir l’application Creative Cloud",
    "Open the {0}Creative Cloud desktop application{1}": "Ouvrir l’{0}application de bureau Creative Cloud{1}",
    "Optimize": "Optimiser",
    "Or see everything you have access to...": "Ou découvrez toutes les fonctionnalités dont vous pouvez bénéficier...",
    "Or see your files, photos, fonts, colors, and portfolio >": "Vous pouvez également consulter votre portfolio et vos fichiers, photos, polices et couleurs >",
    "Or {0}upload{1}{2} from your computer.": "Vous pouvez également {0}charger{1}{2} des documents depuis votre ordinateur.",
    "Other": "Autre",
    "Our apologies but we\\'re experiencing unexpected increased load. We\\'re working quickly to resolve the issue. Please check back or see our {0}status site{1} for updates.": "Malheureusement, nous subissons une surcharge inattendue. Nous tentons de résoudre ce problème au plus vite. Veuillez revenir sur cette page ultérieurement ou consulter l’{0}état du site{1} pour être informé de toute évolution.",
    "Our apologies. We\\'re working hard to resolve the issue.": "Veuillez accepter nos excuses. Nous nous efforçons de corriger le problème au plus vite.",
    "Owner": "Propriétaire",
    "Owner (You)": "Propriétaire (vous)",
    "PB": "NP",
    "PNG 32": "PNG 32",
    "PNG 8 Alpha": "PNG 8 Alpha",
    "Page": "Page",
    "Page Not Found": "Page non trouvée",
    "Page {0} of {1}": "Page {0} sur {1}",
    "Pagination": "Pagination",
    "Password": "Mot de passe",
    "Patterns": "Motifs",
    "Pending Invitations": "Invitations en attente",
    "Pending Invitations ({0})": "Invitations en attente ({0})",
    "Pending Invitations ({0}) {1}Preview{2}": "{1}Aperçu{2} des invitations en attente ({0})",
    "Pending Invites ({0})": "Invitations en attente ({0})",
    "Permanently Delete": "Supprimer définitivement",
    "Please check all that apply": "Cochez toutes les cases appropriées",
    "Please check back again later.": "Veuillez réessayer ultérieurement.",
    "Please close this window and try again.": "Veuillez fermer cette fenêtre et réessayer.",
    "Please enable cookies": "Activer les cookies",
    "Please enable cookies in your browser and reload the page.": "Activez les cookies dans votre navigateur et rechargez la page.",
    "Please enter an email address to share": "Indiquez une adresse e-mail pour procéder au partage",
    "Please provide a description of your concern.": "Merci de décrire le problème rencontré.",
    "Please provide a name for this Design Library.": "Indiquez un nom pour cette bibliothèque de conception.",
    "Please provide a name for this asset.": "Indiquez un nom pour cette ressource.",
    "Please provide a name for this folder.": "Indiquez un nom pour ce dossier.",
    "Please provide a valid Adobe ID and Sign In again.": "Fournissez un ID Adobe valide et cliquez à nouveau sur Se connecter.",
    "Please provide a valid password and Sign In again.": "Fournissez un mot de passe valide et cliquez à nouveau sur Se connecter.",
    "Please provide both an Adobe ID email address and a password and Sign In again.": "Indiquez l’adresse électronique correspondant à votre ID Adobe et votre mot de passe, puis cliquez à nouveau sur Se connecter.",
    "Please select a folder before trying to move this file.": "Veuillez sélectionner un dossier avant de tenter de déplacer ce fichier.",
    "Please select a folder.": "Veuillez sélectionner un dossier.",
    "Please select a reason for the report": "Sélectionnez le motif du rapport",
    "Please verify the password for your Adobe ID ({0}) and Sign In.": "Confirmez le mot de passe correspondant à votre ID Adobe ({0}) et cliquez sur Se connecter.",
    "Please wait a moment": "Veuillez patienter quelques instants.",
    "Please wait for the initial replacement to finish uploading": "Merci de patienter pendant le téléchargement de l’élément de remplacement initial.",
    "Position copied to clipboard": "Position copiée dans le Presse-papiers",
    "Post Publicly": "Message public",
    "Preferred font unit": "Unité de police préférée",
    "Pressing &larr; will select the layer that is parent to the current layer.": "La touche &larr; permet de sélectionner le calque parent du calque actif.",
    "Pressing &ldquo;Esc&rdquo; clears the current selection, exits the current mode, or dismisses a dialog.": "La touche Echap permet d’effacer la sélection en cours, de quitter le mode actif ou de fermer une boîte de dialogue.",
    "Pressing &rarr; will select the first child layer of the current layer. If the currently selected layer has no children, this key does nothing.": "La touche &rarr; permet de sélectionner le premier calque enfant du calque actif. Si le calque actif n’a pas d’éléments enfants, cette touche n’a aucun effet.",
    "Preview": "Aperçu",
    "Privacy Policy": "Politique de confidentialité",
    "Private": "Privé",
    "Processing": "Traitement",
    "Projects": "Projets",
    "Public": "Public",
    "Public Link": "Lien public ",
    "Quality": "Qualité",
    "Racist or Hate Content": "Contenu raciste ou incitant à la haine",
    "Reauthentication is unavailable at this time. Please try again later.": "L’option de réauthentification n’est pas disponible pour le moment. Veuillez réessayer ultérieurement.",
    "Recent": "Récents",
    "Reduction": "Réduction",
    "Regular Select": "Sélection classique",
    "Reject": "Refuser",
    "Remove Access": "Supprimer l’accès",
    "Remove Cover": "Supprimer la couverture",
    "Remove Invitation": "Supprimer l’invitation",
    "Remove Public Link": "Supprimer le lien public",
    "Remove access to this folder": "Supprimer l’accès à ce dossier",
    "Remove invitation": "Supprimer l’invitation",
    "Removing the file extension {0} from this file.": "Suppression de l’extension {0} de ce fichier.",
    "Rename": "Renommer",
    "Renaming...": "Changement de nom en cours...",
    "Rendition conversion failed. Please try again later.": "Echec de conversion du rendu. Veuillez réessayer ultérieurement.",
    "Replace": "Remplacer",
    "Replace file": "Remplacer le fichier",
    "Report Abuse": "Signaler un abus",
    "Report abuse": "Signaler un abus",
    "Request Access": "Demander un accès",
    "Request Early Access": "Demander un accès en avant-première",
    "Required Password Reset": "Réinitialisation du mot de passe obligatoire",
    "Reset Layers": "Réinitialiser les calques",
    "Restore": "Restaurer",
    "Restore Version": "Restaurer la version",
    "Restore {0} items?": "Restaurer {0} éléments ?",
    "Restore {0} to the version from {1}?": "Restaurer {0} à la version dont la date est : {1} ?",
    "Restore {0}?": "Restaurer {0} ?",
    "Restored file \\'{0}\\'.": "Fichier {0} restauré.",
    "Restored folder \\'{0}\\' and all of its content.": "Dossier {0} restauré, ainsi que son contenu.",
    "Restored {0} items.": "{0} éléments restaurés.",
    "Revised {0}": "Révision le {0}",
    "Revisions": "Révisions",
    "SVG": "SVG",
    "Save": "Enregistrer",
    "Save as Image...": "Enregistrer en tant qu’image...",
    "Save optimized images": "Enregistrer des images optimisées",
    "Save the {0} file": "Enregistrez le fichier {0}.",
    "Save {0} Layers as Image...": "Enregistrer les {0} calques en tant qu’image...",
    "Scale at": "Echelle",
    "Schedule {0}Expert 1:1 Support{1}.": "Planifiez une {0}session individuelle avec un expert{1}.",
    "Search": "Rechercher",
    "Search Results": "Résultats de recherche",
    "See everything you have access to...": "Découvrez toutes les fonctionnalités dont vous pouvez bénéficier...",
    "See our {0}blog post{1} to learn more about file syncing on Creative Cloud.": "Consultez ce {0}billet sur notre blog{1} pour en savoir plus sur la synchronisation de fichiers dans Creative Cloud.",
    "See your files, photos, fonts, colors, and portfolio >": "Consultez votre portfolio et vos fichiers, photos, polices et couleurs >",
    "Select First Child": "Sélectionner le premier enfant",
    "Select Parent Layer": "Sélectionner le calque parent",
    "Select a color swatch in the Styles tab to see where the color is used in your design.": "Sélectionnez une nuance de couleur dans l’onglet Styles pour voir où cette couleur est utilisée dans votre composition.",
    "Select a single layer in the PSD to see its CSS properties": "Sélectionnez un seul calque dans le PSD pour voir ses propriétés CSS.",
    "Select files from Creative Cloud": "Sélectionnez des fichiers dans Creative Cloud.",
    "Select layer comps with the drop down above the PSD view.": "Pour sélectionner des compositions de calques, utilisez le menu déroulant qui se trouve au-dessus du PSD.",
    "Selected item(s), including the content of any selected folders, will be moved to the archive. Visit the Archive to permanently delete them from your account.": "Les éléments sélectionnés, ainsi que le contenu des dossiers sélectionnés, vont être déplacés vers les archives. Pour supprimer définitivement ces éléments de votre compte, accédez à la section Archives.",
    "Selected item(s), including the content of any selected folders, will be moved to the archive. Visit the Archive to permanently delete them from your account. {0}This will remove the item(s) for all collaborators.": "Les éléments sélectionnés, ainsi que le contenu des dossiers sélectionnés, vont être déplacés vers les archives. Pour supprimer définitivement ces éléments de votre compte, accédez à la section Archives. {0}Plus aucun collaborateur n’aura accès à ces éléments.",
    "Selected item(s), including the content of any selected folders, will be moved to the owner's Archive. Only they can restore or permanently delete this file.": "Les éléments sélectionnés, ainsi que le contenu des dossiers sélectionnés, vont être déplacés vers les archives de leur propriétaire. Lui seul pourra restaurer ou supprimer définitivement ces fichiers.",
    "Selects or deselects a layer to add it to or remove it from a group of selected layers.": "Permet de sélectionner ou de désélectionner un calque afin de l’ajouter à un groupe de calques ou de l’en supprimer.",
    "Selects the next or previous sibling layer. Pressing &uarr; will select the previous sibling and pressing &darr; will select the next sibling layer.": "Permet de sélectionner le calque frère suivant ou précédent. La touche &uarr; sélectionne le calque frère précédent, la touche &darr; sélectionne le suivant.",
    "Send": "Envoyer",
    "Send Link": "Envoyer le lien",
    "Sending...": "Envoi en cours...",
    "Sent link for \\'{0}\\' to {1}": "Lien envoyé pour \\'{0}\\' à {1}",
    "Sent link for the selected items to {0}": "Lien envoyé à {0} pour les éléments sélectionnés",
    "September": "Septembre",
    "Set \\'{0}\\' as the folder cover for \\'{1}\\'": "Définir « {0} » en tant que couverture du dossier « {1} »",
    "Settings": "Paramètres",
    "Settings for '{0}' have been cleared.": "Les paramètres pour {0} ont été effacés.",
    "Sexually Explicit Content": "Contenu sexuellement explicite",
    "Share": "Partager",
    "Share information with other DPS members": "Partager des informations avec les autres membres DPS",
    "Shared Folders": "Dossiers partagés",
    "Shared by {0}.": "Partagé par {0}.",
    "Shortcuts": "Raccourcis",
    "Show Cover": "Afficher la couverture",
    "Show Folder Covers": "Affichage de la page de couverture des dossiers",
    "Show Less": "Montrer moins",
    "Show More": "Montrer plus",
    "Sign In / Sign Up": "Se connecter/S’enregistrer",
    "Sign Out": "Se déconnecter",
    "Sign in": "Se connecter",
    "Sign in is unavailable at this time. Please try again later.": "Connexion impossible pour le moment. Veuillez réessayer ultérieurement.",
    "Sign in to Creative Cloud with your Adobe ID.": "Connectez-vous à Creative Cloud avec votre ID Adobe.",
    "Sign in with your Adobe ID": "Connectez-vous avec votre ID Adobe",
    "Sign out": "Se déconnecter",
    "Sign out is unavailable at this time. Please try again later.": "Déconnexion impossible pour le moment. Veuillez réessayer ultérieurement.",
    "Sign up": "S’enregistrer",
    "Sign up for a free Creative Cloud account to collaborate on the folder {0} and get 2GB of free cloud storage.": "Inscrivez-vous pour ouvrir un compte Creative Cloud gratuit, collaborer sur le dossier {0} et bénéficier de 2 Go d’espace de stockage offerts dans le cloud.",
    "Sign up is unavailable at this time. Please try again later.": "Inscription impossible pour le moment. Veuillez réessayer ultérieurement.",
    "Signing in...": "Connexion en cours...",
    "Single Edition allows a designer to use Adobe InDesign to build an iPad app with engaging elements such as slideshows, embedded audio and video, image pan, zoom and panoramas, 360-degree object rotation and more - all without writing code. Using only tools created by Adobe, you can create engaging apps with lots of interactivity. The apps built can be submitted and sold through the Apple App Store. Single Edition is now included as part of an Adobe Creative Cloud membership. The following instructions will help you get started!": "L’édition Single permet aux concepteurs d’utiliser Adobe InDesign afin de créer une application pour iPad contenant des éléments attractifs, comme des diaporamas, des vidéos et des sons intégrés, un panoramique sur les images, des fonctions de zoom et de panorama, la rotation des objets à 360 degrés, et bien plus encore, tout cela sans écrire le moindre code. Simplement à l’aide des outils mis au point par Adobe, vous pouvez créer des applications séduisantes, avec une grande interactivité. Les applications ainsi créées peuvent être envoyées et vendues par le biais de l’App Store d’Apple. L’édition Single est désormais incluse dans les abonnements Adobe Creative Cloud. Les instructions ci-après vous aideront à vous familiariser avec le produit.",
    "Size": "Taille ",
    "Size copied to clipboard": "Taille copiée dans le Presse-papiers",
    "Sorry, an error has occurred.": "Désolé, une erreur est survenue.",
    "Sorry, but Behance requires images that are at least {0} pixels wide and {1} pixels tall.": "Erreur, Behance requiert des images d’au moins {0} pixels de large et {1} pixels de haut.",
    "Sorry, but the following characters may not be used in file names: |, &quot;, ?, <, >, /, \\\\, :, *. {0}Learn More{1}.": "Erreur, l’utilisation des caractères suivants n’est pas autorisée dans les noms de fichiers : |, &quot;, ?, <, >, /, \\\\, :, *. {0}En savoir plus{1}.",
    "Sorry, the Collaboration feature is not yet available.": "Désolé, la fonction Collaboration n’est pas encore disponible.",
    "Sorry, this browser does not support that specific drag-and-drop behavior.": "Désolé, ce navigateur ne prend pas en charge cette action spécifique de glisser-déposer.",
    "Sorry, this invitation has been accepted or revoked.": "Erreur, cette invitation a déjà été acceptée ou a été révoquée.",
    "Sorry, this link is no longer active.": "Désolé, ce lien n’est plus actif.",
    "Sorry, this resource can not be publicly shared.": "Désolé, cette ressource ne peut pas faire l’objet d’un partage public.",
    "Sorry, we're having some technical difficulties.": "Veuillez nous excuser, nous rencontrons quelques difficultés techniques.",
    "Sorry, you are trying to view an invitation that no longer exists. This is most likely because you already accepted the invitation.": "Désolé, vous tentez d’accéder à une invitation qui n’existe plus. Vous avez probablement déjà accepté cette invitation.",
    "Sorry, you are trying to view an invitation that was not sent to this account. Please log in using the email address to which the invitation was sent, or ask the person who invited you to resend the invitation to this account.": "Désolé, vous tentez d’accéder à une invitation qui a été envoyée à un autre compte. Connectez-vous avec l’adresse e-mail à laquelle l’invitation a été envoyée, ou demandez à l’expéditeur de vous renvoyer l’invitation sur le compte actif.",
    "Sorry, you have exceeded your storage quota.": "Vous avez malheureusement atteint votre quota de stockage.",
    "Sort": "Trier",
    "Start and maintain your website online": "Création et mise à jour de votre site web en ligne",
    "Still Having Trouble?": "Le problème persiste ?",
    "Storage": "Stockage",
    "Storage plans": "Formules de stockage",
    "Store your files in the cloud to access your creativity from any device.": "Stockez vos fichiers dans le cloud pour accéder à vos créations depuis n’importe quel périphérique.",
    "Streamline your workflow with link sharing &amp; folder collaboration.": "Rationalisez votre flux de travail grâce au partage de liens et à la collaboration au sein de dossiers.",
    "Styles": "Styles",
    "Sync From Your Desktop": "Synchroniser depuis le bureau",
    "TB": "To",
    "Team Management": "Gestion d’équipe",
    "Temporary Sites ({0})": "Sites temporaires ({0})",
    "Terms of Use": "Conditions d’utilisation",
    "Test": "Tester",
    "Text copied to clipboard": "Texte copié dans le Presse-papiers",
    "Thank you for signing up. Keep an eye on your email for an early access invitation!": "Merci pour votre inscription. Consultez régulièrement votre messagerie pour voir si vous avez reçu une invitation à profiter d’un accès en avant-première !",
    "Thank you for signing up. Keep an eye on your email for an invitation!": "Merci pour votre inscription. Consultez régulièrement votre messagerie pour voir si vous avez reçu une invitation.",
    "Thank you for your patience.": "Nous vous remercions de votre patience.",
    "Thank you! Please check your email for instructions on verifying your email address.": "Merci. Consultez votre messagerie afin de prendre connaissance des instructions de vérification de votre adresse électronique.",
    "Thank you, {0}.": "Merci, {0}.",
    "Thanks for your patience!": "Merci de votre patience !",
    "The Adobe Application Manager lets you download every app available on Creative Cloud straight to your desktop.": "Adobe Application Manager vous permet de télécharger toutes les applications disponibles dans Creative Cloud, directement sur votre poste de travail.",
    "The Adobe ID and/or password provided does not appear to be valid. Please try again.": "L’ID Adobe et/ou le mot de passe fournis ne semblent pas valides. Veuillez réessayer.",
    "The Creative Cloud Download Center is currently unavailable.": "Le Centre de téléchargement Creative Cloud est actuellement indisponible.",
    "The archive is empty.": "L’archive est vide.",
    "The early access program has concluded and Adobe has now made file sync available to all users.": "Le programme d’accès en avant-première proposé par Adobe est terminé, la synchronisation de fichiers est désormais accessible à tous.",
    "The email address provided has either already been verified or did not match an account on file.": "L’adresse électronique indiquée a déjà été validée ou ne correspond à aucun compte enregistré.",
    "The maximum number of collaborators has been reached.": "Le nombre maximal de collaborateurs a été atteint.",
    "The provided email address could not be matched to an account on file. Please try again.": "L’adresse électronique indiquée ne correspond à aucun compte enregistré. Veuillez réessayer.",
    "The public url has been sent to {0}": "L’URL publique a été envoyée à {0}.",
    "The verification email has been sent. Please check your inbox and click the link to verify.": "Le courrier électronique de vérification vous a été envoyé. Consultez votre messagerie et cliquez sur le lien pour confirmer.",
    "The {0} name entered exceeds the 255 character limit and may have been truncated.": "Le nom entré {0} dépasse la limite des 255 caractères et peut avoir été tronqué.",
    "There are no comments for this item yet.": "Aucun commentaire pour cet élément pour le moment.",
    "There was a problem sharing your file. Please try again later.": "Un problème est survenu lors du partage du fichier. Veuillez réessayer ultérieurement.",
    "There was an error moving {0} items": "Erreur lors du déplacement de {0} élément(s)",
    "There was an error submitting your report, please try again": "Une erreur s’est produite lors de l’envoi de votre rapport. Veuillez réessayer",
    "These people can view, edit, rename, move, or delete the contents of this Design Library. They can also invite or remove collaborators.": "Ces utilisateurs peuvent consulter, modifier, renommer, déplacer et supprimer le contenu de cette bibliothèque de conception. Ils peuvent également inviter des collaborateurs ou supprimer leur accès au dossier.",
    "These people can view, edit, rename, move, or delete the contents of this folder. They can also invite or remove collaborators.": "Ces utilisateurs peuvent consulter, modifier, renommer, déplacer et supprimer le contenu de ce dossier. Ils peuvent également inviter des collaborateurs ou supprimer leur accès au dossier.",
    "This action will remove your access to the selected shared folder(s). Other collaborators will still have access.": "Après cette action, vous n’aurez plus accès au(x) dossier(s) partagé(s) sélectionné(s). Les autres collaborateurs y auront toujours accès.",
    "This feature is not yet implemented": "Cette fonctionnalité n’est pas encore implémentée",
    "This file is larger than the current version. You don't have enough space left to restore it. Please permanently delete other files to make room.": "Ce fichier est plus volumineux que la version actuelle. L’espace dont vous disposez est insuffisant pour le restaurer. Veuillez supprimer d’autres fichiers de façon permanente pour libérer de l’espace.",
    "This folder is empty": "Ce dossier est vide.",
    "This folder is empty.": "Ce dossier est vide.",
    "This layer contains blend modes that may not be rendered correctly with the current combination of visible layers.": "Ce calque contient des modes de fusion qui risquent de ne pas s’afficher correctement avec la combinaison actuelle de calques visibles.",
    "This layer contains font substitutions so the font-size CSS reported is approximate.": "Ce calque contient des substitutions de polices, de sorte qu’il est possible que le code CSS de taille de police indiqué soit approximatif.",
    "This page is taking too long to load.": "La page met trop de temps à se charger.",
    "This page is temporarily unavailable. We\\'ll be back soon.": "Cette page est temporairement indisponible. Elle sera rétablie dès que possible.",
    "This search did not return any results.": "La recherche n’a renvoyé aucun résultat.",
    "This video introduces the general process of building your first folio, the content for your app. For additional tips and techniques, download Adobe\\'s free {0}DPS Tips{1} application from the Apple App Store and read the &quot;Single Edition&quot; issue.": "Cette vidéo explique brièvement comment créer votre premier folio, c’est-à-dire le contenu de votre application. Pour obtenir des conseils et apprendre de nouvelles techniques, téléchargez gratuitement l’application Adobe {0}DPS Tips{1} depuis l’App Store d’Apple et lisez le document « Single Edition ».",
    "This video introduces the process involved in establishing an iOS developer membership with Apple. For detailed instructions, refer to the &quot;Enroll in Apple\\'s iOS Developer Program&quot; section in the Step-by-Step Guide.": "Cette vidéo explique comment valider votre adhésion en tant que développeur iOS auprès d’Apple. Pour obtenir des instructions détaillées, reportez-vous à la section « Adhésion au programme de développement iOS d’Apple » du Guide détaillé.",
    "This video provides an overview of the tools used in the Single Edition workflow, terminology and requirements. Refer to the &quot;Introduction&quot; section in the Step-by-Step Guide.": "Cette vidéo propose un aperçu des outils utilisés dans le workflow de l’édition Single, présente la terminologie utilisée et détaille les conditions requises. Reportez-vous à la section « Introduction » du Guide détaillé.",
    "Tip: ": "Conseil : ",
    "Title": "Titre",
    "Title required": "Titre obligatoire",
    "To access this site, please upgrade your browser. Read our {0}system requirements{1} for more information.": "Pour accéder à ce site, merci de mettre à niveau votre navigateur. Pour en savoir plus, prenez connaissance de la {0}configuration minimale requise{1}.",
    "To free up space, try permanently deleting files": "Pour libérer de l’espace, essayez de supprimer des fichiers de façon définitive.",
    "To free up space, try permanently deleting files from your {0}.": "Pour libérer de l’espace, essayez de supprimer des fichiers de façon définitive sur votre {0}.",
    "To get below your limit, please permanently delete files": "Pour repasser en-dessous de la limite autorisée, veuillez supprimer des fichiers de façon définitive.",
    "To get started, install the free {0}desktop app{1}.": "Pour démarrer, installez gratuitement l’{0}application de bureau {1}.",
    "To get started, just install the free {0}Creative Cloud desktop app{1}. If you already have it installed, simply relaunch the app. Then, go to the Files panel to start syncing.": "Pour démarrer, il vous suffit d’installer gratuitement l’{0}application de bureau Creative Cloud{1}. Si c’est déjà fait, relancez simplement l’application, puis ouvrez le panneau Fichiers pour commencer la synchronisation.",
    "To protect the security of your account, you must reset your password. Please check your inbox for an email we just sent you with instructions for how to reset your password and log into your account.": "Afin de garantir la sécurité de votre compte, vous devez réinitialiser votre mot de passe. Reportez-vous à l'e-mail que nous venons de vous envoyer pour savoir comment réinitialiser votre mot de passe et vous connecter à votre compte.",
    "To remove your settings files from Creative Cloud, click {0}Clear Settings{1} below.": "Pour supprimer vos fichiers de paramètres de Creative Cloud, cliquez sur {0}Effacer les paramètres{1} ci-dessous.",
    "To report a Copyright Violation, please follow Section 17 in the {0}Terms of Use{1}.": "Pour signaler un cas de violation des droits d’auteur, veuillez vous reporter à la section 17 des {0}Conditions d’utilisation{1}.",
    "Today": "Aujourd’hui",
    "Toggle Measurement Tooltip": "Activer l’info-bulle de mesure",
    "Toggle Show Info on hover": "Activer l’option « Afficher les infos » par pointage",
    "Toggles measurement tooltip on hover.": "Permet d’afficher l’info-bulle de mesure en pointant sur l’élément avec la souris.",
    "Trademark Infringement": "Contrefaçon de marque commerciale",
    "Trouble signing in?": "Problèmes de connexion ?",
    "Try Extract for PSD to web workflows": "Essayez Extract pour passer de fichiers PSD à des fichiers Web",
    "Try refreshing your browser or see our ": "Essayez d’actualiser votre navigateur ou consultez notre ",
    "Type": "Type",
    "Uh oh, this PSD has an exceptional number of layers and has failed to process.": "Erreur, ce PSD comporte un nombre très élevé de calques et n’a pas pu être traité.",
    "Uh oh, this PSD has an exceptional number of layers and has failed to process. Please keep the number of layers below {0}. This PSD has {1}.": "Erreur, ce PSD comporte un nombre très élevé de calques et n’a pas pu être traité. Le nombre de calques ne doit pas excéder {0}. Ce PSD en contient {1}.",
    "Uh oh, this PSD was not successfully processed because it's not currently compatible with Extract.": "Erreur, ce PSD n’a pas été traité correctement car il n’est pas compatible avec Extract.",
    "Unable to Connect to Behance": "Impossible de se connecter à Behance",
    "Undo": "Annuler",
    "Upgrade": "Mise à niveau",
    "Upload": "Télécharger",
    "Upload Your Files": "Charger des fichiers",
    "Upload a PSD": "Charger un fichier PSD",
    "Upload complete": "Téléchargement terminé",
    "Upload failed: an item named {0} already exists.": "Echec du chargement : il existe déjà un élément portant le nom {0}.",
    "Upload files": "Transférer les fichiers",
    "Uploaded": "Chargé",
    "Uploading .app archive files is not supported. Please try again with a different file type.": "Le téléchargement de fichiers d’archive .app n’est pas pris en charge. Veuillez réessayer avec un autre type de fichier.",
    "Uploading folders is not supported. Create a folder first, then drag your files into it.": "Le téléchargement de dossiers n’est pas pris en charge. Créez un dossier, puis faites-y glisser vos fichiers.",
    "Uploading this type of file or folder is not supported via drag-and-drop.": "Il est impossible de transférer ce type de fichier ou de dossier par glisser-déposer.",
    "Uploading...": "Téléchargement en cours…",
    "Use Extract for PSD to web workflows": "Utilisez Extract pour passer de fichiers PSD à des fichiers Web",
    "Use an existing Account": "Utiliser un compte existant",
    "Use as Cover": "Utiliser comme couverture",
    "Use shift-click to measure the distance between elements in the PSD view.": "Pour mesurer la distance entre deux éléments dans le PSD, appuyez sur la touche Maj tout en cliquant sur chaque élément.",
    "Use the arrow keys to traverse the layers in your design.": "Utilisez les flèches pour traverser les calques de votre composition.",
    "Use the desktop application to find information about software updates, see release notes, connect with your creative community, and manage synced files": "Utilisez l’application de bureau pour obtenir des informations sur les mises à jour logicielles, consulter les notes de mise à jour, rejoindre la communauté de créateurs et gérer vos fichiers synchronisés.",
    "Use the desktop application to install the programs you need, find information about software updates, sync and share files, and connect with the rest of your team": "Utilisez l’application de bureau pour installer les programmes dont vous avez besoin, obtenir des informations sur les mises à jour logicielles, synchroniser et partager des fichiers, mais aussi rester en contact permanent avec le reste de votre équipe.",
    "Use the {0}file chooser{1}{2} to upload files.": "Utilisez le {0}sélecteur de fichier{1}{2} pour charger des fichiers.",
    "Use this folder": "Utiliser ce dossier",
    "Useful CSS here": "Code CSS utile ici",
    "User Interfaces": "Interfaces utilisateur",
    "User profile is unavailable at this time. Please try again later.": "Le profil d’utilisateur n’est pas disponible pour le moment. Veuillez réessayer ultérieurement.",
    "Valid description required": "Fournir une description valide",
    "Valid email required": "Fournir une adresse électronique valide",
    "Valid name required": "Fournir un nom valide",
    "Value copied to clipboard": "Valeur copiée dans le Presse-papiers",
    "Vector Shapes": "Formes vectorielles",
    "Versions": "Versions",
    "Video": "Vidéo",
    "Video 1: Workflow for Creative Cloud and Digital Publishing Suite Single Edition": "Vidéo 1 : Workflow pour Creative Cloud et Digital Publishing Suite édition Single",
    "Video 2: Preparing for Single Edition": "Vidéo 2 : Préparatifs pour l’édition Single",
    "Video 2: Preparing to build your Single Edition app": "Vidéo 2 : Préparatifs pour la création d’une application édition Single",
    "Video 3: Creating your Single Edition folio": "Vidéo 3 : Création de votre folio édition Single",
    "Video 3: Creating your folio": "Vidéo 3 : Création de votre folio",
    "Video 4: Building your Single Edition app": "Vidéo 4 : Développement de votre application édition Single",
    "Video 4: Building your app": "Vidéo 4 : Développement de votre application",
    "Video 5: Submitting your Single Edition app": "Vidéo 5 : Envoi de votre application édition Single",
    "Video 5: Submitting your app": "Vidéo 5 : Envoi de votre application",
    "View": "Afficher",
    "View Archive": "Afficher l’archive",
    "View archive": "Voir les archives",
    "View archived files": "Voir les fichiers archivés",
    "View design library: {0}": "Voir la bibliothèque de conception : {0}",
    "View folder: {0}": "Afficher le dossier : {0}",
    "View less": "Voir moins",
    "View more": "Afficher plus",
    "View overview topics and detailed instructions": "Consulter les rubriques de présentation et les instructions détaillées",
    "View publications created using Digital Publishing Suite": "Consultez des publications créées avec Digital Publishing Suite.",
    "Warning: This layer contains an incompatible graphic option: blend mode": "Avertissement : ce calque contient une option graphique non compatible : mode de fusion",
    "Watch instructional videos about digital publishing": "Regardez des vidéos instructives sur la publication numérique.",
    "Watch more videos": "Voir plus de vidéos",
    "Watch more videos from our expert partners": "Voir plus de vidéos de nos partenaires et experts",
    "We are performing planned maintenance on this page and will have it back up shortly. We apologize for any inconvenience. For updates on site maintenance, please visit our {2}status site{3}.": "Une intervention de maintenance prévue est en cours ; cette page sera à nouveau accessible très prochainement. Nous vous prions de nous excuser pour les éventuels désagréments occasionnés. Pour être informé des opérations de maintenance planifiées, consultez la page sur l’{2}état du site{3}.",
    "We can\\'t find the page you\\'re looking for. {0} View {1}your files{2} or browse {3}your apps and services{4}.": "Nous ne trouvons pas la page que vous recherchez. {0} Consultez {1}vos fichiers{2} ou parcourez {3}vos applications et services{4}.",
    "We couldn't find your collaboration invitation, it may have already been accepted, expired, or revoked by the sender.": "Nous ne parvenons pas à trouver votre invitation, celle-ci a peut-être déjà été accepté, a expiré ou a été révoquée par son expéditeur.",
    "We sent you an email": "Nous vous avons envoyé un courrier électronique",
    "We use the standard W3C SVG format which is supported by all viewers.": "Nous utilisons le format SVG W3C standard, qui est compatible avec tous les lecteurs.",
    "We were unable to create your folder. Please try again later.": "Nous n’avons pas pu créer votre dossier. Veuillez réessayer ultérieurement.",
    "We were unable to send an email to {0}. Please try again later.": "Nous n’avons pas pu envoyer de message électronique à {0}. Réessayez ultérieurement.",
    "We're sorry, but we can't complete this upload because it would exceed our limit for the maximum number of items in your account. Please empty your archive or delete some items and try again.": "Malheureusement, ce chargement ne peut aboutir car votre compte comporterait alors plus d’éléments que la limite autorisée. Videz vos archives ou supprimez quelques éléments et réessayez.",
    "We're sorry, but you can't archive these items because your archive is too full. Please permanently delete some items in your archive and try again.": "Malheureusement, vous ne pouvez pas archiver ces éléments car vos archives sont pleines. Supprimez définitivement quelques éléments de vos archives et réessayez.",
    "We're sorry, but you can't archive this item because your archive is too full. Please permanently delete some items in your archive and try again.": "Malheureusement, vous ne pouvez pas archiver cet élément car vos archives sont pleines. Supprimez définitivement quelques éléments de vos archives et réessayez.",
    "We're sorry, but you can't create a new folder because it would exceed our limit for the maximum number of items in your account. Please empty your archive or delete some items and try again.": "Malheureusement, vous ne pouvez plus créer de dossier car votre compte comporterait alors plus d’éléments que la limite autorisée. Videz vos archives ou supprimez quelques éléments et réessayez.",
    "We're sorry, but you can't create a new folder because it would exceed our limit for the maximum number of nested subfolders. Please create your new folder in a different directory.": "Malheureusement, vous ne pouvez plus créer de dossier ici : vous dépasseriez alors le nombre maximum de sous-dossiers imbriqués. Vous pouvez créer votre dossier dans un autre répertoire.",
    "We're sorry, but you can't move new items to this folder because it would exceed our limit for the maximum number of items per folder. Please delete some items and try again.": "Malheureusement, vous ne pouvez plus déplacer d’éléments vers ce dossier car la limite fixée a été atteinte. Supprimez quelques éléments et réessayez.",
    "We're sorry, but you can't move this folder because the destination folder has exceeded our limit for the maximum number of nested subfolders. Please move this folder to a different directory.": "Malheureusement, vous ne pouvez pas déplacer ce dossier car le dossier de destination excède le nombre maximum de sous-dossiers imbriqués. Vous pouvez déplacer ce dossier vers un autre répertoire.",
    "We're sorry. You can't share this folder because at least one of its sub-folders has collaborators.{0} To share this folder, first remove all collaborators from its sub-folders, then re-invite everyone to this folder. When you add collaborators to a folder, its sub-folders are automatically shared with the same people.": "Désolé, vous ne pouvez pas partager ce dossier car au moins l’un de ses sous-dossiers est associé à des collaborateurs.{0} Pour partager ce dossier, supprimez d’abord tous les collaborateurs des sous-dossiers, puis réinvitez chacun à collaborer sur le dossier lui-même. Lorsque vous ajoutez des collaborateurs à un dossier, ses sous-dossiers sont automatiquement partagés avec les mêmes personnes.",
    "We\\'re rolling out file sync in limited batches to Creative Cloud members. Sign up here to register for early access. We\\'ll add you to the waiting list, and send you an email once you\\'re in.": "Nous déployons actuellement la synchronisation de fichiers en octroyant un nombre limité d’accès aux membres Creative Cloud. Inscrivez-vous ici pour bénéficier d’un accès en avant-première. Vous serez ajouté à la liste d’attente et recevrez un e-mail une fois que votre demande aura abouti.",
    "We\\'re sorry, this file cannot be shared due to the detection of copyrighted material. {0}Learn more{1}.": "Désolé, ce fichier ne peut pas être partagé, il est protégé par copyright. {0}En savoir plus{1}.",
    "We\\'re sorry, this file type cannot be shared at this time. {0}Learn more{1}.": "Désolé, il n’est pas possible de partager ce type de fichier pour le moment. {0}En savoir plus{1}.",
    "We\\'re sorry, we had trouble adding your comment. Please refresh the page and try again.": "Malheureusement, nous ne sommes pas parvenus à ajouter votre commentaire. Veuillez actualiser la page et réessayer.",
    "We\\'re sorry. Something seems to be wrong on our end. Please {0}try again{1} later. If this continues to fail, please contact {2}Customer Support{3}.": "Désolé, un problème semble être survenu. Veuillez {0}réessayer{1} ultérieurement. Si le problème persiste, contactez le {2}Service clientèle{3}.",
    "We\\'re sorry. We have encountered an error while processing your cancellation. Please contact {0}Customer Support{1} to cancel your membership.": "Une erreur s’est produite pendant le traitement de votre demande de résiliation. Veuillez contacter le {0}Service clientèle{1} pour résilier votre abonnement.",
    "We\\'re working quickly to resolve the issue and we apologize for the delay. If you have the Creative Cloud app already installed on your machine, you can try using it to access new downloads and updates. Otherwise, please check back or see our {0}status site{1} for updates.": "Nous tentons de résoudre ce problème au plus vite et nous excusons de cette attente. Si l’application Creative Cloud est déjà installée sur votre ordinateur, vous pouvez tenter de l’utiliser pour accéder aux nouveaux téléchargements et mises à jour. Dans le cas contraire, revenez sur cette page ultérieurement ou consultez l’{0}état du site{1} pour être informé de toute évolution.",
    "We\\'re working quickly to resolve the issue and we\\'re sorry for the delay. Please check back or see our {0}status site{1} for updates. Also, help is available in the {2}Creative Cloud forums{3}.": "Nous tentons de résoudre ce problème au plus vite et nous excusons de cette attente. Veuillez revenir sur cette page ultérieurement ou consulter l’{0}état du site{1} pour être informé de toute évolution. Vous pouvez également obtenir de l’aide sur les {2}forums Creative Cloud{3}.",
    "We\\'re working quickly to resolve the issue and we\\'re sorry for the delay. Please check back or see our {0}status site{1} for updates. Also, help is available in the {2}forums{3}.": "Nous tentons de résoudre ce problème au plus vite et nous excusons de cette attente. Veuillez revenir sur cette page ultérieurement ou consulter l’{0}état du site{1} pour être informé de toute évolution. Vous pouvez également obtenir de l’aide sur les {2}forums{3}.",
    "We\\'re working to improve the overall performance of the Creative Cloud files experience. Your account will be accessible again shortly. Please check back in a few minutes.": "Nous nous efforçons d’améliorer les performances globales du service Creative Cloud Files. Vous pourrez bientôt accéder de nouveau à votre compte. Revenez sur cette page dans quelques minutes.",
    "Website design without coding": "Conception de sites web sans codage",
    "Website, app design, and coding": "Sites web, conception d’applications et codage",
    "Websites": "Sites web",
    "Welcome to Creative Cloud": "Bienvenue dans Creative Cloud",
    "Welcome to Creative Cloud Files": "Bienvenue dans Creative Cloud Files",
    "What are you reporting?": "Quel type de problème souhaitez-vous signaler ?",
    "What is Adobe Digital Publishing Suite, Single Edition?": "Qu’est-ce qu’Adobe Digital Publishing Suite, édition Single ?",
    "Why are you reporting this content?": "Pour quel motif effectuez-vous un signalement de ce contenu ?",
    "Width": "Largeur",
    "With Digital Publishing Suite, Single Edition, you can use familiar InDesign skills to create, develop, and deliver iPad apps like brochures, portfolios, yearbooks and annual reports&#8212;with engaging interactive elements such as slideshows, embedded audio and video, pan and zoom images, panoramas, 360-degree object rotation and more&#8212;without writing code. Single Edition is now included as part of Adobe Creative Cloud. With a Creative Cloud membership, you can build an unlimited number of iPad apps and submit to the Apple App Store. Follow these instructions to get started!": "Avec Digital Publishing Suite, édition Single, vous pouvez exploiter vos compétences InDesign habituelles pour créer, développer et publier des applications pour iPad telles que des brochures, des dossiers de présentation, des annuaires et des rapports annuels (comportant des éléments interactifs attractifs comme des diaporamas, des sons et des films intégrés, des images avec zoom et panoramique, des panoramas, la rotation d’objets à 360 degrés, et bien plus encore), le tout sans écrire le moindre code. L’édition Single est désormais intégrée à Adobe Creative Cloud. Avec un abonnement Creative Cloud, vous pouvez créer un nombre illimité d’applications pour iPad et les envoyer à l’App Store d’Apple. Pour vous lancer, suivez les instructions fournies !",
    "Working...": "Traitement en cours...",
    "Yes": "Oui",
    "Yesterday": "Hier",
    "You": "Vous ",
    "You are not allowed to share this file.": "Vous n’êtes pas autorisé à partager ce fichier.",
    "You can only replace this file with another {0} file.": "Vous pouvez uniquement remplacer ce fichier par un autre fichier {0}.",
    "You can select multiple layers in the Layers tab and export them as a single image.": "Il est possible de sélectionner plusieurs calques dans l’onglet Calques et de les exporter en tant qu’image unique.",
    "You can\\'t upload new files while over your storage limit. Please permanently delete files from the Archive and try again.": "Vous ne pouvez plus charger de nouveaux fichiers tant que vous dépassez la limite de stockage autorisée. Supprimez définitivement quelques fichiers de vos archives et réessayez.",
    "You currently do not have any synced settings.": "Vous n’avez pas encore synchronisé de paramètres.",
    "You done goofed.": "Vous avez fait une erreur.",
    "You have made too many failed Sign In attempts with this Adobe ID and we have temporarily locked this address. Please try again in a few minutes.": "Le nombre de tentatives de connexion infructueuses avec cet ID Adobe a été dépassé et votre adresse a été temporairement bloquée. Veuillez réessayer dans quelques minutes.",
    "You have no archived files.": "Vous n’avez aucun fichier archivé.",
    "You have no more pending invitations": "Vous n’avez plus d’invitations en attente",
    "You have no pending invitations.": "Vous n’avez pas d’invitation en attente.",
    "You have restored to the version from {0}.": "Vous avez restauré la version dont la date est : {0}.",
    "You left the folder: {0}": "Vous avez quitté le dossier suivant : {0}",
    "You must {0}verify your email address{1} in order to make this file public by clicking the link provided in the verification email.": "Pour publier ce fichier, vous devez {0}confirmer votre adresse électronique{1} en cliquant sur le lien fourni dans le courrier électronique de vérification.",
    "You\\'re about to install the Adobe Application Manager": "Vous êtes sur le point d’installer Adobe Application Manager",
    "You\\'re about to install {0}": "Vous êtes sur le point d’installer {0}",
    "You\\'re signed in using": "Vous êtes connecté avec l’identifiant",
    "You\\'re {0} over your storage limit.": "Vous avez {0} en trop par rapport à votre limite de stockage.",
    "Your Email": "Votre adresse électronique",
    "Your Name": "Votre nom",
    "Your account is undergoing routine maintenance.": "Votre compte est en cours de maintenance.",
    "Your browser is no longer supported and you may have trouble using certain features. Please upgrade your browser. Read our {0}system requirements{1} for more information.": "Votre navigateur n’est plus pris en charge et certaines options risquent de ne pas fonctionner correctement. Merci de mettre à niveau votre navigateur. Pour en savoir plus, prenez connaissance de la {0}configuration minimale requise{1}.",
    "Your browser is no longer supported.": "Votre navigateur n’est plus pris en charge.",
    "Your browser may ask you to accept the download": "Votre navigateur vous demandera peut-être d’accepter le téléchargement.",
    "Your cloud storage is almost full.": "Votre espace de stockage dans le cloud est quasiment plein.",
    "Your email address has not been verified. {0}Click here{1} to send an email with verification instructions.": "Votre adresse électronique n’a pas été vérifiée. {0}Cliquez ici{1} pour recevoir un courrier électronique indiquant les instructions de vérification.",
    "Your file has been shared with {0}": "Votre fichier a été partagé avec {0}.",
    "Your files are importing and will appear momentarily": "Vos fichiers sont en cours d’importation et s’afficheront dans quelques instants",
    "Your folder can not be created. Please remove any characters that are not letters or numbers and try again.": "Impossible de créer votre dossier. Supprimez les caractères autres que des lettres et des chiffres, puis réessayez.",
    "Your folder name ends with a period (.) which is not allowed. Please remove the character or try another name.": "Le nom de votre dossier se termine par un point (.), ce qui n’est pas autorisé. Supprimez ce caractère ou utilisez un autre nom.",
    "Your payment has been processed.": "Votre paiement a été traité.",
    "Your redemption code has been applied.": "Votre code d’échange a été appliqué.",
    "Your report has been submitted": "Votre rapport a été envoyé",
    "Your search did not match any files": "La recherche n’a renvoyé aucun fichier.",
    "Your storage plan has been changed to {0}.{1}It may take a few minutes for you to see the update to your total storage.": "Votre formule de stockage a été modifiée et correspond maintenant à {0}.{1}La mise à jour de votre capacité de stockage totale peut prendre quelques minutes.",
    "Zoom": "Zoom",
    "Zoom in and out on your PSD view using ALT +/-.": "Pour effectuer un zoom avant ou arrière sur votre PSD, utilisez les touches ALT +/-.",
    "Zoom preview canvas in and out.": "Zoom avant et arrière sur l’aperçu de la zone de travail.",
    "Zoom to 100%": "Zoomer à 100 %",
    "Zoom to fit width in view": "Zoomer selon la largeur de la fenêtre",
    "already joined": "déjà membre",
    "archive": "Archiver",
    "at {0}": "à {0}",
    "back": "Retour",
    "by {0}": "par {0}",
    "clear": "effacer",
    "color swatch": "nuance de couleur",
    "default": "par défaut",
    "file": "fichier",
    "folder": "dossier",
    "for updates.": "pour rechercher d’éventuelles mises à jour.",
    "here": "ici",
    "invited again": "réinvité",
    "just now": "à l’instant",
    "loading...": "chargement en cours...",
    "no subfolders": "aucun sous-dossier",
    "of": "sur",
    "or": "ou",
    "original": "original",
    "status page ": "page de statut ",
    "submitted": "envoyé",
    "test": "test",
    "the provided email addresses": "les adresses électroniques indiquées",
    "true": "TRUE",
    "{0} B": "{0} octets",
    "{0} file was too large and did not upload.": "{0} fichier est trop volumineux et n’a pas pu être chargé.",
    "{0} file was too large and did not upload. Please download {1} to sync files larger than {2}.": "{0} fichier est trop volumineux et n’a pas pu être chargé. Veuillez télécharger {1} pour synchroniser les fichiers dont la taille excède {2}.",
    "{0} files were too large and did not upload.": "{0} fichiers sont trop volumineux et n’ont pas pu être chargés.",
    "{0} files were too large and did not upload. Please download {1} to sync files larger than {2}.": "{0} fichiers sont trop volumineux et n’ont pas pu être chargés. Veuillez télécharger {1} pour synchroniser les fichiers dont la taille excède {2}.",
    "{0} has been deleted": "{0} a été supprimé",
    "{0} has been restored": "{0} a été restauré",
    "{0} has invited you to the folder {1}. To view the folder, sign into Creative Cloud using your Adobe ID or create one now for free.": "{0} vous invite à collaborer sur le dossier {1}. Pour y accéder, connectez-vous à Creative Cloud avec votre ID Adobe ou créez-vous un compte gratuitement.",
    "{0} hour ago": "il y a {0} heure",
    "{0} hours ago": "il y a {0} heures",
    "{0} items have been deleted": "{0} éléments ont été supprimés",
    "{0} items have been restored": "{0} éléments ont été restaurés",
    "{0} minute ago": "il y a {0} minute.",
    "{0} minutes ago": "il y a {0} minutes.",
    "{0} of {1}": "{0} sur {1}",
    "{0} selected": "{0} sélectionné(s)",
    "{0}-{1} of {2}": "{0}-{1} sur {2}",
    "{0}B": "{0}octets",
    "{0}Begin{1}{2} storing, sharing and collaborating on your work.": "{0}Commencez{1}{2} à stocker vos travaux, à les partager et à collaborer avec d’autres utilisateurs.",
    "{0}GB": "{0} Go",
    "{0}Private{1}: Only you can view this {2}. Create a public link to share a read-only view of this {3} with others.": "{0}Privé{1} : Vous seul pouvez consulter ce {2}. Créez un lien public pour partager une version en lecture seule de ce {3} avec d’autres personnes.",
    "{0}Public{1}: Anyone with the link can view this {2}. Remove the link to make the {3} private again.": "{0}Public{1} : Toute personne disposant du lien peut consulter ce {2}. Supprimez le lien pour que ce {3} redevienne privé.",
    "{0}The Download Center{1} is still available to download apps.": "Le {0}Centre de téléchargement{1} est toujours disponible pour télécharger les applications de votre choix.",
    "{0}px": "{0} px"
});