/*
 * ADOBE CONFIDENTIAL
 *
 * Copyright (c) 2014 Adobe Systems Incorporated. All rights reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe Systems Incorporated and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Adobe Systems Incorporated and its
 * suppliers and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe Systems Incorporated.
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

/*
 *
 * Do *NOT* translate the string keys on the left of the colon.  These string
 *    keys *MUST* match the string values used in the JS.
 *
 * This file contains the translate() table copied from the last pull of Extract CCW.
 * The English language `root` strings are embedded directly in the JS.  However,
 *   the localized strings for this language will be provided in the table below.
 *
 */

define({
    "&copy; 2014 Adobe Systems Incorporated. All Rights Reserved.": "&copy; 2014 Adobe Systems Incorporated. All Rights Reserved.",
    "&copy; 2014 Adobe Systems Software Ireland Ltd. All Rights Reserved.": "&copy; 2014 Adobe Systems Software Ireland Ltd. All Rights Reserved.",
    "(updated)": "(更新)",
    "1": "1",
    "1 {0} file is being downloaded.": "1 {0} ファイルをダウンロードしています。",
    "1. Upload your PSD to Creative Cloud Files.": "1. Creative Cloud Files に PSD をアップロードします。",
    "2": "2",
    "2. Share your PSD with others.": "2. PSD を他のユーザーと共有します。",
    "256 colors. Lowest file size. Alpha transparency to be retained if present in element.": "256 色。最小ファイルサイズ。アルファ透明度が要素に存在する場合は保持。",
    "3": "3",
    "3. Enable others to extract CSS, colors, fonts and more.": "3. CSS、カラー、フォントなどを他のユーザーが抽出できるようにします。",
    "4": "4",
    "5": "5",
    "</p>": "</p>",
    "<span>1.</span> Create your site with the app that\\'s right for you": "<span>1.</span> 最適なアプリケーションを使用してサイトを作成します",
    "<span>2.</span> Push your site live with Adobe Web Hosting": "<span>2.</span> Adobe Web Hosting を使用してサイトを公開します",
    "A file with that name already exists. Please rename your file and try again.": "同じ名前のファイルが既に存在します。ファイル名を変更して、もう一度お試しください。",
    "A folder with that name already exists in this folder.": "このフォルダーには同じ名前のフォルダーが既に存在しています。",
    "A valid email address is required.": "有効な電子メールアドレスが必要です。",
    "ALT +/- to zoom in and out": "ALT + プラス (+) / マイナス (-) キーをクリックして拡大・縮小",
    "Accept": "同意する",
    "Accepted 1 invitation. Added {0} to Creative Cloud.": "1 件の招待を承認しました。{0} を Creative Cloud に追加しました。",
    "Access": "アクセス",
    "Action": "アクション",
    "Actions": "アクション",
    "Activity": "アクティビティ",
    "Add": "追加",
    "Add Comment": "コメントを追加",
    "Add Optional Description": "オプションの説明を追加",
    "Add Required Title": "必要なタイトルを追加",
    "Add comment": "コメントを追加",
    "Add new licenses for your team and invite new members. Don\\'t forget to assign a license to yourself if you\\'d like to use apps from Creative Cloud as well!": "グループに新しいライセンスを追加し、新しいメンバーを招待します。ご自身も Creative Cloud アプリケーションを使用する場合は、自分自身にもライセンスを割り当ててください。",
    "Added file \\'{0}\\'.": "ファイル「{0}」が追加されました。",
    "Added folder \\'{0}\\'.": "フォルダー「{0}」が追加されました。",
    "Added {0} items.": "{0} アイテムが追加されました。",
    "Adding...": "追加しています...",
    "Adobe Add-ons": "Adobe Add-ons",
    "Adobe Add-ons is currently unavailable.": "Adobe Add-ons は現在使用できません。",
    "Adobe Brushes": "Adobe ブラシ",
    "Adobe Creative Cloud": "Adobe Creative Cloud",
    "Adobe Creative Cloud requires JavaScript in order to load properly. Please enable JavaScript in your browser and reload the page.": "Adobe Creative Cloud で正しく読み込みを行うには、JavaScript が必要です。ご使用のブラウザーで JavaScript を有効にして、ページを再読み込みしてください。",
    "Adobe Creative Cloud requires cookies to be enabled in order to load properly. Please enable cookies in your browser and reload the page.": "Adobe Creative Cloud で正しく読み込みを行うには、Cookie が有効に設定されている必要があります。ご使用のブラウザーで Cookie を有効にして、ページを再読み込みしてください。",
    "Adobe Sketch": "Adobe Sketch",
    "Adobe TV Videos": "Adobe TV ビデオ",
    "Adobe Web Hosting lets you easily publish desktop and mobile-friendly websites created using Adobe Muse or Dreamweaver. Hosting for five sites is included as part of your Creative Cloud membership.": "Adobe Web Hosting を使用すれば、Adobe Muse や Dreamweaver で作成したデスクトップおよびモバイル対応の Web サイトを簡単にパブリッシュできます。Creative Cloud メンバーシップには 5 つのサイトのホストが含まれています。",
    "Adobe&nbsp;Creative&nbsp;Cloud Maintenance": "Adobe&nbsp;Creative&nbsp;Cloud メンテナンス中",
    "Adobe&reg;&nbsp;Creative&nbsp;Cloud&#153; requires cookies to be enabled in order to load properly.": "Adobe® Creative Cloud™ を正しく読み込むには Cookie を有効にする必要があります。",
    "Advanced Options": "詳細オプション",
    "After building and testing your app, your final step is to submit it to the Apple App Store. This video covers the basics involved. For detailed instructions, refer to the &quot;Submit to the App Store&quot; section of the Step-by-Step Guide.": "アプリケーションを作成してテストが完了したら、最後に Apple App Store に申請します。このビデオでは、その基本情報をご説明します。詳しくは、ステップバイステップガイドの「App Store への申請」をご覧ください。",
    "After extracting assets, find them in the Assets tab where they can be downloaded locally.": "アセットを抽出したら、「アセット」タブでローカルにダウンロードして表示できます。",
    "All": "すべて",
    "All Activity": "すべての履歴",
    "All Categories": "全カテゴリー",
    "All settings have been cleared.": "すべての設定がクリアされました。",
    "All you need is an Adobe ID": "必要なものは Adobe ID のみ",
    "Allow File Download": "ファイルのダウンロードを許可",
    "Allow use of {0}": "{0} の使用を許可",
    "Allows extraction of pixel-level color values.": "ピクセルレベルでカラー値を抽出できます。",
    "Already have an Adobe ID?": "Adobe ID をお持ちの場合",
    "Already have it installed? Relaunch the app and go to the Files panel to start syncing.": "既にインストール済みの場合は、アプリケーションを再起動してファイルパネルから同期を開始できます。",
    "An email with instructions for resetting your password has already been sent. Please check your email, or try again in a few minutes.": "パスワードをリセットするための手順が記載された電子メールを送信しました。電子メールを確認するか、少し時間をおいてから再試行してください。",
    "An error occured, please try again.": "エラーが発生しました。もう一度実行してください。",
    "An error occurred, please refresh your browser and try again.": "エラーが発生しました。ブラウザーを更新してからもう一度実行してください。",
    "An error occurred, please try again.": "エラーが発生しました。もう一度実行してください。",
    "An item with that name already exists in this folder.": "このフォルダーには同じ名前のアイテムが既に存在しています。",
    "An unexpected error occurred. Please try again later.": "予期しないエラーが発生しました。後でもう一度実行してください。",
    "Application settings are synced between many of your favorite desktop applications and Creative Cloud, allowing you to work consistently from any machine. To begin syncing, you will need to open your desktop application and click {0}Sync Settings Now{1}.": "ご使用のデスクトップアプリケーションのアプリケーション設定を Creative Cloud に同期すると、どのマシンからでも同じ設定を使用することができます。同期を開始するには、デスクトップアプリケーションを開いて、{0}今すぐ同期{1}をクリックします。",
    "Application settings are temporarily unavailable. Please try again later.": "現在、アプリケーションの設定を利用できません。後でもう一度実行してください。",
    "Apply": "適用",
    "Approximation due to font substitution": "フォント置換による類似",
    "April": "4 月",
    "Archive": "アーカイブ",
    "Archive {0} item(s)?": "{0} 個のアイテムをアーカイブしますか？",
    "Ascending": "昇順",
    "Ask experts in the {0}forums{1}.": "{0}フォーラム{1}でエキスパートに質問",
    "Assets": "アセット",
    "August": "8 月",
    "B": "B",
    "Base font size": "基本フォントサイズ",
    "Browse files within {0}": "ファイルを {0} で参照する",
    "Browse for the program you need and install it": "必要なプログラムを探してインストールしてください",
    "Browse for the program you need and {0}install it directly from your Creative Cloud desktop application{1}": "必要なプログラムを探して{0}Creative Cloud デスクトップアプリケーションから直接インストールしてください{1}",
    "Brushes": "ブラシ",
    "Business Catalyst Site Builder": "Business Catalyst Site Builder",
    "By Date": "変更日順",
    "By Name": "名前順",
    "By Size": "サイズ順",
    "By Type": "種類順",
    "By signing up for the Early Access program, you agree to Adobe\\'s {0}Terms of Use{1} and {2}Privacy Policy{3}.": "先行アクセスプログラムに登録することにより、アドビの{0}利用条件{1}および{2}プライバシーポリシー{3}に同意したことになります。",
    "CSS copied to clipboard": "クリップボードに CSS がコピーされました",
    "Cancel": "キャンセル",
    "Category": "カテゴリー",
    "Changing the file extension from {0} to {1}.": "ファイルの拡張子を {0} から {1} に変更します。",
    "Choose a file format to download": "ダウンロードするファイル形式を選択",
    "Choose a folder": "フォルダーを選択",
    "Clear All": "すべて消去",
    "Clear Settings": "設定を消去",
    "Clear/Exit": "消去 / 終了",
    "Click Extract to do all this in your browser:": "「Extract」をクリックすると、ブラウザーで以下のことを行うことができます。",
    "Click to copy": "クリックしてコピー",
    "Click to download": "クリックしてダウンロード",
    "Close": "閉じる",
    "Collaborate": "フォルダー共有",
    "Collaborate with {0}": "{0} とのフォルダー共有",
    "Collaborators": "フォルダー共有者",
    "Collaborators {0}Preview{1}": "共有者 {0}プレビュー{1}",
    "Color Picker": "カラーピッカー",
    "Colors": "カラー",
    "Combine feature set(s)": "機能セットを結合",
    "Comment &amp; version history helps you track changes - and gives you peace of mind.": "コメントやバージョン履歴で変更履歴を確認できるので、安心して作業できます。",
    "Comment required": "コメントが必要です",
    "Comments": "コメント",
    "Contact Behance Help": "Behance ヘルプにアクセス",
    "Converting Image...": "画像を変換中...",
    "Cookies": "Cookie",
    "Copied": "コピー済み",
    "Copy": "コピー",
    "Copy All": "すべてコピー",
    "Copy CSS": "CSS をコピー",
    "Copy Text": "テキストをコピー",
    "Copy text and CSS": "テキストおよび CSS をコピー",
    "Copyright": "著作権",
    "Create Folder": "フォルダーを作成",
    "Create Public Link": "公開リンクを作成",
    "Create a new Adobe ID": "新しい Adobe ID の作成",
    "Create an Adobe ID": "Adobe ID を作成",
    "Created new folder \\'{0}\\'": "新規フォルダー「{0}」を作成",
    "Creative Cloud": "Creative Cloud",
    "Creative Cloud Connection": "Creative Cloud Connection",
    "Creative Cloud Assets": "Creative Cloud アセット",
    "Creative Cloud Files is currently unavailable.": "Creative Cloud Files は現在利用できません。",
    "Creative Cloud has experienced an unexpected Sign In failure. Please try again later.": "Creative Cloud で予期しないサインインエラーが発生しました。後でもう一度実行してください。",
    "Creative Cloud is currently experiencing issues with a small number of file types. Previews and download conversions will be delayed for these files. We are working to resolve these issues as quickly as possible. Thank you for your patience.": "Creative Cloud では、現在、いくつかのファイルタイプについて問題が発生しています。これらのファイルでは、プレビューおよびダウンロードに遅れが生じます。この問題については早急に対処いたしますので、しばらくお待ちください。",
    "Creative Cloud is currently unavailable. We will be back online as soon as possible. Thank you for your patience!": "Creative Cloud は現在使用できません。復旧まで今しばらくお待ちください。ご迷惑をおかけして申し訳ございません。",
    "Creative Cloud is currently undergoing maintenance. Please check back later. Thank you for your patience.": "Creative Cloud は現在メンテナンス中です。しばらく時間をおいてからご確認ください。ご迷惑をおかけして申し訳ございません。",
    "Current Version": "現在のバージョン",
    "December": "12 月",
    "Declined 1 invitation.": "1 件の招待を拒否しました。",
    "Defamation": "中傷",
    "Delete Asset": "アセットを削除",
    "Delete Comment": "コメントを削除",
    "Delete comment by {0}?": "{0} さんのコメントを削除しますか？",
    "Delete {0} items?": "{0} アイテムを削除しますか？",
    "Delete {0}?": "{0} を削除しますか？",
    "Descending": "降順",
    "Description": "説明",
    "Design Libraries": "デザインライブラリ",
    "Desktop": "デスクトップ",
    "Desktop Sync Settings": "アプリケーション設定の同期",
    "Details": "詳細",
    "Did this work as expected?": "正常に機能しましたか？",
    "Digital Publishing Gallery": "Digital Publishing ギャラリー",
    "Digital Publishing Suite Help": "Digital Publishing Suite ヘルプ",
    "Digital Publishing Support Forums": "Digital Publishing サポートフォーラム",
    "Direct Select": "パス選択",
    "Done": "完了",
    "Download": "ダウンロード",
    "Download Center": "ダウンロードセンター",
    "Download the Creative Cloud app": "Creative Cloud アプリをダウンロード",
    "Download the Step-by-Step Guide to Publishing iPad Apps with DPS, Single Edition": "DPS Single Edition を使用して iPad アプリケーションを公開するためのステップバイステップガイドをダウンロードする",
    "Download the {0}Creative Cloud desktop application{1} and install it on your machine (or ask your IT administrator to install it for you)": "{0}Creative Cloud デスクトップアプリケーション{1}をダウンロードしてコンピューターにインストールしてください (または、IT 管理者にインストールを依頼してください)",
    "Download the {0}Creative Cloud desktop application{1}, which will help you manage all your favorite Adobe applications directly from your desktop": "{0}Creative Cloud デスクトップアプリケーション{1}をダウンロードしてください。すべてのお好きなアドビアプリケーションをデスクトップから直接管理することができます。",
    "Downloaded": "ダウンロード済み",
    "Drag Files Here": "ファイルをここにドラッグ",
    "Drag and drop your files here, or use the {0}file chooser{1}{2}.": "ファイルをここにドラッグ＆ドロップするか、{0}ファイル選択{1}{2}を使用してください。",
    "Easily manage your Creative Cloud licenses by clicking on the Get Started button below.": "Creative Cloud ライセンスの管理を簡単にするには、以下の「使用を開始」ボタンをクリックしてください。",
    "Email": "電子メール",
    "Email address": "電子メール アドレス",
    "Empty Archive": "空のアーカイブ",
    "Emptying Archive": "アーカイブを空にしています",
    "Emptying archive...": "アーカイブを空にしています...",
    "Enter email address": "電子メールアドレスを入力",
    "Enter the email address you use for your Adobe ID and we will send you instructions.": "Adobe ID で使用している電子メールアドレスを入力してください。手順を記載した電子メールをお送りします。",
    "Error extracting asset.": "アセットの抽出中にエラーが発生しました。",
    "Error extracting asset. You've possibly exceeded your storage limit.": "アセットの抽出中にエラーが発生しました。ストレージ容量の上限を超過している可能性があります。",
    "Error retrieving derived assets ({0})": "派生アセット ({0}) の取得エラー",
    "Extract": "Extract",
    "Extract FAQ": "FAQ を抽出",
    "Extract Forums": "Extract フォーラム",
    "Extract Help": "ヘルプを抽出",
    "Extract asset": "アセットを抽出",
    "Extract asset at specified scale factor": "指定したスケール比率でアセットを抽出",
    "Extract helps web designers and developers turn PSD comps into code-based designs &mdash; in the browser.": "Extract を使用すると、Web デザイナーや開発者はブラウザーで PSD のカンプをコードベースのデザインに変換できます。",
    "Extract requires a minimum width of 800 pixels": "Extract の最小幅は 800 pixel です",
    "Extracted Assets": "抽出されたアセット",
    "Extracting asset. Look for it in the Assets tab.": "アセットを抽出しています。「アセット」タブで確認してください。",
    "Eyedropper Tool": "スポイトツール",
    "FIT": "全体表示",
    "Failed to load plugin: {0}": "プラグインの読み込みに失敗しました: {0}",
    "Featured": "おすすめ",
    "February": "2 月",
    "File Sync is Now Available": "ファイルの同期機能をご利用いただけます",
    "File and font sync is now activated for Creative Cloud members with annual or monthly subscription plans.": "Creative Cloud の年間メンバーシップまたはサブスクリプションプランをお持ちの方に、ファイルとフォントの同期機能の提供を開始しました。",
    "File information": "ファイル情報",
    "Files": "ファイル",
    "Files and folders you own will be archived and you will be removed from collaboration on folders owned by others.": "所有しているファイルやフォルダーはアーカイブされ、自身も他の人が所有しているフォルダーの共有から削除されます。",
    "Find answers to common questions {0}here{1}.": "一般的な質問に対する回答については、{0}こちら{1}をご参照ください。",
    "Find font on typekit.com": "typekit.com でフォントを検索する",
    "Find the {0} and open it to start installation": "{0} を起動してインストールを開始します",
    "First User Experience Guide (i)": "ファーストユーザーエクスペリエンスガイド (i)",
    "First, the Adobe Application Manager will download": "まず、Adobe Application Manager をダウンロードします",
    "Folder names must not be blank.": "フォルダー名は空白にすることはできません。",
    "Follow the instructions to create a new password.": "手順に従って、新しいパスワードを設定してください。",
    "Fonts": "フォント",
    "For Placement": "画像",
    "Forgot Your Password?": "パスワードを忘れた場合",
    "Forgot password?": "パスワードを忘れた場合",
    "Format": "フォーマット",
    "Full Creative Cloud Membership comes with hosting for up to 5 sites. View and manage these sites from the sidebar on the Creative Cloud home page.": "有料の Creative Cloud メンバーシップに登録すると、最大 5 つのサイトをホストすることができます。これらのサイトは、Creative Cloud ホームページのサイドバーから表示および管理します。",
    "GB": "GB",
    "Get Access to File and Font Sync": "ファイルとフォントの同期機能を入手",
    "Get Early Access to File Sync": "ファイルの同期機能をお試しください",
    "Get Started": "今すぐ始める",
    "Get color, gradient, and font info": "カラー、グラデーション、フォント情報を見る",
    "Get started": "今すぐ始める",
    "Get started on your website": "web サイトの作成と管理",
    "Getting started with Adobe Digital Publishing Suite, Single Edition": "Adobe Digital Publishing Suite, Single Edition ファーストステップガイド",
    "Go to Comments to preview the PSD.": "コメントに移動して PSD をプレビューします。",
    "Go to Details to preview the PSD.": "詳細に移動して PSD をプレビューします。",
    "Go to your downloads folder": "ダウンロードフォルダーに移動します",
    "Gradients": "グラデーション",
    "Height": "高さ",
    "Help": "ヘルプ",
    "Help is available in the {0}Creative Cloud forums{1}.": "サポートが必要な場合は、{0}Creative Cloud フォーラム{1}でご質問ください。",
    "Here\\'s what\\'s next": "次のステップ",
    "Hi": "ご利用ありがとうございます。",
    "Hide Folder Covers": "フォルダーカバーを非表示",
    "Home": "ホーム",
    "Hover over thumbnails in the Layers tab to see a preview for a layer or layer group.": "「レイヤー」タブでサムネイルをホバーして、レイヤーまたはレイヤーグループのプレビューを表示します。",
    "I don&#39;t know my Adobe ID": "自分の Adobe ID がわかりません",
    "Icons": "アイコン",
    "If you feel that this Creative Cloud content violates the Adobe {0}Terms of Use{1}, you may report this content by filling out this quick form.": "この Creative Cloud コンテンツがアドビの{0}利用条件{1}に違反しているとお考えの場合は、このクイックフォームに記入することで、報告できます。",
    "If you\\'d like, download Creative Cloud Packager to simplify the software installation process and quickly get your team members set up.": "Creative Cloud Packager を使用すると、ソフトウェアのインストール処理を簡単にし、グループメンバーのセットアップを迅速に行うことができます。",
    "If you\\'re a free member and don\\'t yet have a subscription plan, you can sign up here to turn on file sync. We\\'ll add you to the waiting list, and send you an email once you have access.": "無償メンバーシップをご利用の方で、まだサブスクリプションプランをお持ちでない場合は、ファイルの同期機能を有効にするために、こちらでサインアップをしてください。お客様を順番待ちリストに追加させていただき、準備が整い次第、電子メールにてご連絡差し上げます。",
    "Image": "画像",
    "Import": "読み込み",
    "Import Files": "ファイルをインポート",
    "Info": "情報",
    "Inline Style": "インラインスタイル",
    "Interested in trying our Additional Storage offering? Contact {0}Customer Support{1} to sign up for early access.": "追加ストレージの提供をお試しいただく場合は、{0}カスタマーサポート{1}にご連絡いただき、先行アクセスプログラムにサインアップしてください。",
    "Invitation Not Found": "招待状が見つかりません",
    "Invite": "招待",
    "Invite not found.": "招待が見つかりません。",
    "Invited": "招待済み",
    "It lets you download every app available on Creative Cloud straight to your desktop.": "Creative Cloud で使用可能なすべてのアプリケーションを、直接デスクトップにダウンロードするツールです。",
    "It\\'s great to see you here with the rest of your team. Let\\'s get started so you can get down to business.": "グループにようこそ。さっそく使い始めましょう。",
    "It\\'s great to see you here. Let\\'s get started so you can get down to business.": "Creative Cloud へようこそ。さっそく使い始めましょう。",
    "Item(s) Archived.": "アイテムをアーカイブしました。",
    "JPG": "JPG",
    "January": "1 月",
    "JavaScript Disabled!": "JavaScript が無効です",
    "Job queued...": "キューにジョブを登録しました...",
    "July": "7 月",
    "June": "6 月",
    "KB": "KB",
    "Keep me signed in": "サインイン状態を保持する",
    "Keyboard Shortcuts": "キーボードショートカット",
    "Keyboard Shortcuts Guide (?)": "キーボードショートカットガイド (?)",
    "Language:": "言語:",
    "Last Document State": "最後のドキュメント状態",
    "Launch Site Builder": "Site Builder を起動",
    "Launched Sites ({0})": "公開済みのサイト ({0})",
    "Layers": "レイヤー",
    "Learn": "トレーニング",
    "Learn More": "さらに詳しく",
    "Learn More.": "さらに詳しく",
    "Leave Folder": "共有から外れる",
    "Leave folder": "共有から外れる",
    "Leave folders": "フォルダーを残す",
    "Leave {0}": "{0} を残す",
    "Libraries": "ライブラリ",
    "List": "リスト",
    "Loading...": "読み込み中...",
    "Lossless format so better quality.": "高品質なロスレスフォーマット",
    "MB": "MB",
    "Made With": "制作情報",
    "Make Playable": "再生可能にする",
    "Manage": "管理",
    "Manage Collaborators": "共有者の管理",
    "March": "3 月",
    "Market": "マーケット",
    "Market Assets": "マーケットアセット",
    "May": "5 月",
    "Measure between elements": "エレメント間を計測",
    "Min Sheets": "最小シート数",
    "Mobile": "モバイル",
    "Mobile Assets": "モバイルアセット",
    "Modified": "更新日時",
    "Mosaic": "タイル",
    "Most Relevant": "関連性の高い順",
    "Move": "移動",
    "Move to '{0}'": "{0} に移動",
    "Move to folder": "フォルダーに移動",
    "Move {0} items": "{0} アイテムを移動",
    "Moved 1 item into \\'{0}\\'": "1 アイテムを {0} に移動しました。",
    "Moved file \\'{0}\\' to the archive.": "ファイル {0} をアーカイブに移動しました。",
    "Moved folder \\'{0}\\' and all of its content to the archive.": "フォルダー {0} とその中のファイルをすべてアーカイブに移動しました。",
    "Moved {0} items into \\'{1}\\'": "{0} アイテムを {1} に移動しました。",
    "Moved {0} items to the archive.": "{0} アイテムをアーカイブに移動しました。",
    "Moving \\'{0}\\'": "「{0}」を移動中",
    "Moving {0} items": "{0} 個のアイテムを移動中",
    "Moving...": "移動中...",
    "Multi-Select": "複数選択",
    "Multiple Revisions": "複数バージョン",
    "Multiple files may not be used to replace. Please select a single file.": "複数のファイルで置き換えることはできません。単一のファイルを選択してください。",
    "My Assets": "マイアセット",
    "My Websites": "Web サイト",
    "Name": "名前",
    "Name required": "名前を入力してください",
    "Need an Adobe ID?": "Adobe ID をお持ちでない場合",
    "Next/Previous Sibling Layer": "次または前の兄弟レイヤー",
    "No": "いいえ",
    "No launched sites": "公開済みのサイトがありません",
    "No results": "該当するものはありません",
    "No temporary sites": "一時的なサイトがありません",
    "Not your Adobe ID?": "ご自分の Adobe ID ではない場合",
    "November": "11 月",
    "Now that you\\'ve built your content, it\\'s time to build your app. This video introduces how to use DPS App Builder to generate your app. Refer to the &quot;Build the App with DPS App Builder&quot; section in the Step-by-Step Guide.": "コンテンツを作成したら、次はアプリケーションを作成します。このビデオでは、DPS App Builder を使用したアプリケーション作成の方法をご説明します。ステップバイステップガイドの「DPS App Builder でアプリケーションを作成」をご覧ください。",
    "OK": "OK",
    "October": "10 月",
    "Offensive Content": "不快なコンテンツ",
    "Open the Creative Cloud app": "Creative Cloud アプリケーションを開く",
    "Open the {0}Creative Cloud desktop application{1}": "{0}Creative Cloud デスクトップアプリケーション{1}を開く",
    "Optimize": "最適化",
    "Or see everything you have access to...": "ご利用できる製品はこちらからご確認ください。",
    "Or see your files, photos, fonts, colors, and portfolio >": "また、ファイル、写真、フォント、カラー、ポートフォリオを確認できます >",
    "Or {0}upload{1}{2} from your computer.": "または、お使いのコンピューターから{0}アップロード{1}{2}してください。",
    "Other": "その他",
    "Our apologies but we\\'re experiencing unexpected increased load. We\\'re working quickly to resolve the issue. Please check back or see our {0}status site{1} for updates.": "申し訳ありません。予期しない負荷増加により、現在利用できません。この問題の解決に向けて対応中です。後でまた確認するか、{0}ステータスサイト{1}で状況をご確認ください。",
    "Our apologies. We\\'re working hard to resolve the issue.": "申し訳ありません。この問題の解決に向けて対応中です。",
    "Owner": "所有者",
    "Owner (You)": "所有者 (自分)",
    "PB": "PB",
    "PNG 32": "PNG 32",
    "PNG 8 Alpha": "PNG 8 Alpha",
    "Page": "ページ",
    "Page Not Found": "ページが見つかりません",
    "Page {0} of {1}": "{0}/{1} ページ",
    "Pagination": "ページ番号割り付け",
    "Password": "パスワード",
    "Patterns": "パターン",
    "Pending Invitations": "保留中の招待",
    "Pending Invitations ({0})": "保留中の招待 ({0})",
    "Pending Invitations ({0}) {1}Preview{2}": "保留中の招待 ({0}) {1}プレビュー{2}",
    "Pending Invites ({0})": "保留中の招待 ({0})",
    "Permanently Delete": "完全に削除",
    "Please check all that apply": "適用するすべてを選択してください",
    "Please check back again later.": "後でもう一度ご確認ください。",
    "Please close this window and try again.": "このウィンドウを閉じて、もう一度実行してください。",
    "Please enable cookies": "クッキーを有効にしてください",
    "Please enable cookies in your browser and reload the page.": "ブラウザーの Cookie を有効にしてから再度ページを読み込んでください。",
    "Please enter an email address to share": "共有するには宛先の電子メールアドレスを入力してください",
    "Please provide a description of your concern.": "お客様の懸念事項を詳しくお書きください。",
    "Please provide a name for this Design Library.": "このデザインライブラリの名前を指定してください。",
    "Please provide a name for this asset.": "このアセットの名前を指定してください。",
    "Please provide a name for this folder.": "このフォルダーの名前を指定してください。",
    "Please provide a valid Adobe ID and Sign In again.": "有効な Adobe ID を使用してサインインしてください。",
    "Please provide a valid password and Sign In again.": "有効なパスワードを使用してサインインし直してください。",
    "Please provide both an Adobe ID email address and a password and Sign In again.": "Adobe ID の電子メールアドレスとパスワードの両方を入力して、サインインし直してください。",
    "Please select a folder before trying to move this file.": "このファイルを移動する前にフォルダーを選択してください。",
    "Please select a folder.": "フォルダーを選択してください。",
    "Please select a reason for the report": "レポートの理由を選択してください",
    "Please verify the password for your Adobe ID ({0}) and Sign In.": "Adobe ID ({0}) のパスワードを確認してサインインしてください。",
    "Please wait a moment": "しばらくお待ちください",
    "Please wait for the initial replacement to finish uploading": "最初の置き換えのアップロードが完了するまでお待ちください",
    "Position copied to clipboard": "位置をクリップボードにコピーしました",
    "Post Publicly": "投稿して公開",
    "Preferred font unit": "使用するフォント単位",
    "Pressing &larr; will select the layer that is parent to the current layer.": "&larr; キーを押すと、現在のレイヤーの親レイヤーを選択します。",
    "Pressing &ldquo;Esc&rdquo; clears the current selection, exits the current mode, or dismisses a dialog.": "Esc キーを押すと、現在の選択を解除したり、現在のモードを終了したり、ダイアログを閉じたりできます。",
    "Pressing &rarr; will select the first child layer of the current layer. If the currently selected layer has no children, this key does nothing.": "&rarr; キーを押すと、現在のレイヤーの最初の子レイヤーを選択します。子レイヤーがない場合は、何も起こりません。",
    "Preview": "プレビュー",
    "Privacy Policy": "プライバシーポリシー",
    "Private": "非公開",
    "Processing": "処理中",
    "Projects": "プロジェクト",
    "Public": "公開",
    "Public Link": "公開リンク",
    "Quality": "画質",
    "Racist or Hate Content": "差別または憎悪を含む内容",
    "Reauthentication is unavailable at this time. Please try again later.": "現在、再認証を使用できません。後でもう一度試してください。",
    "Recent": "最近使用したファイル",
    "Reduction": "リダクション",
    "Regular Select": "標準選択",
    "Reject": "拒否",
    "Remove Access": "アクセスの削除",
    "Remove Cover": "表紙を削除",
    "Remove Invitation": "招待を削除",
    "Remove Public Link": "公開リンクを削除",
    "Remove access to this folder": "このフォルダーへのアクセスを削除します",
    "Remove invitation": "招待を削除",
    "Removing the file extension {0} from this file.": "このファイルから拡張子 {0} を削除します。",
    "Rename": "名前の変更",
    "Renaming...": "名前を変更しています...",
    "Rendition conversion failed. Please try again later.": "レンディションの変換に失敗しました。しばらく待ってからもう一度実行してください。",
    "Replace": "置き換え",
    "Replace file": "ファイルを置き換え",
    "Report Abuse": "迷惑行為の報告",
    "Report abuse": "迷惑行為の報告",
    "Request Access": "アクセスを申し込む",
    "Request Early Access": "先行アクセスプログラムに登録",
    "Required Password Reset": "パスワードを変更してください",
    "Reset Layers": "レイヤーをリセット",
    "Restore": "復元",
    "Restore Version": "バージョンの復元",
    "Restore {0} items?": "{0} アイテムを復元しますか？",
    "Restore {0} to the version from {1}?": "{0} を {1} のバージョンに復元しますか？",
    "Restore {0}?": "{0} を復元しますか？",
    "Restored file \\'{0}\\'.": "ファイル {0} を復元しました。",
    "Restored folder \\'{0}\\' and all of its content.": "フォルダー {0} とその中のファイルをすべて復元しました。",
    "Restored {0} items.": "{0} アイテムを復元しました。",
    "Revised {0}": "更新 {0}",
    "Revisions": "変更履歴",
    "SVG": "SVG",
    "Save": "保存",
    "Save as Image...": "画像として保存...",
    "Save optimized images": "最適化された画像を保存",
    "Save the {0} file": "{0} ファイルを保存します",
    "Save {0} Layers as Image...": "{0} レイヤーを画像として保存...",
    "Scale at": "拡大縮小",
    "Schedule {0}Expert 1:1 Support{1}.": "{0}エキスパートサービス{1}を申し込みます。",
    "Search": "検索",
    "Search Results": "検索結果",
    "See everything you have access to...": "アクセスできるものをご確認ください。",
    "See our {0}blog post{1} to learn more about file syncing on Creative Cloud.": "Creative Cloud のファイルの同期についての詳細は、{0}ブログ記事{1}をご覧ください。",
    "See your files, photos, fonts, colors, and portfolio >": "ファイル、写真、フォント、カラー、ポートフォリオを確認できます >",
    "Select First Child": "最初の子を選択",
    "Select Parent Layer": "親レイヤーを選択",
    "Select a color swatch in the Styles tab to see where the color is used in your design.": "「スタイル」タブでカラースウォッチを選択して、カラーが使用されている場所を表示します。",
    "Select a single layer in the PSD to see its CSS properties": "PSD の単一のレイヤーを選択して CSS プロパティを見る",
    "Select files from Creative Cloud": "Creative Cloud からファイルを選択",
    "Select layer comps with the drop down above the PSD view.": "PSD ビューの上にあるドロップダウンでレイヤーカンプを選択します。",
    "Selected item(s), including the content of any selected folders, will be moved to the archive. Visit the Archive to permanently delete them from your account.": "選択したフォルダーの内容も含め、選択したアイテムはアーカイブに移動されます。アーカイブにアクセスし、アカウントからそれらのアイテムを完全に削除してください。",
    "Selected item(s), including the content of any selected folders, will be moved to the archive. Visit the Archive to permanently delete them from your account. {0}This will remove the item(s) for all collaborators.": "選択したフォルダーの内容も含め、選択したアイテムはアーカイブに移動されます。アーカイブにアクセスし、アカウントからそれらのアイテムを完全に削除してください。{0}この操作を行うと、すべての共同作業者のアイテムが削除されます。",
    "Selected item(s), including the content of any selected folders, will be moved to the owner's Archive. Only they can restore or permanently delete this file.": "選択したフォルダーの内容も含め、選択したアイテムは所有者のアーカイブに移動されます。このファイルを復元または完全に削除できるのは所有者のみです。",
    "Selects or deselects a layer to add it to or remove it from a group of selected layers.": "レイヤーを選択または選択解除して、選択したレイヤーのグループに追加またはグループから削除します。",
    "Selects the next or previous sibling layer. Pressing &uarr; will select the previous sibling and pressing &darr; will select the next sibling layer.": "次または前の兄弟レイヤーを選択します。&uarr; キーを押すと前の兄弟レイヤーを選択し、&darr; キーを押すと次の兄弟レイヤーを選択します。",
    "Send": "送信",
    "Send Link": "リンクを送信",
    "Sending...": "送信中...",
    "Sent link for \\'{0}\\' to {1}": "「{0}」のリンクを {1} に送信しました",
    "Sent link for the selected items to {0}": "選択したアイテムのリンクを {0} に送信しました",
    "September": "9 月",
    "Set \\'{0}\\' as the folder cover for \\'{1}\\'": "「{0}」を「{1}」のフォルダーカバーとして設定",
    "Settings": "設定",
    "Settings for '{0}' have been cleared.": "「{0}」 の設定がクリアされました。",
    "Sexually Explicit Content": "露骨な性表現を含む内容",
    "Share": "共有",
    "Share information with other DPS members": "他の DPS ユーザーと情報を共有",
    "Shared Folders": "共有フォルダー",
    "Shared by {0}.": "{0} さんが共有に招待しました。",
    "Shortcuts": "ショートカット",
    "Show Cover": "表紙を表示",
    "Show Folder Covers": "フォルダーカバーを表示",
    "Show Less": "一部を表示",
    "Show More": "すべてを表示",
    "Sign In / Sign Up": "サインイン / サインアップ",
    "Sign Out": "サインアウト",
    "Sign in": "サインイン",
    "Sign in is unavailable at this time. Please try again later.": "現在サインインができません。後でもう一度試してください。",
    "Sign in to Creative Cloud with your Adobe ID.": "Adobe ID で Creative Cloud にサインインしてください。",
    "Sign in with your Adobe ID": "Adobe ID を使用してサインイン",
    "Sign out": "サインアウト",
    "Sign out is unavailable at this time. Please try again later.": "現在サインアウトができません。後でもう一度試してください。",
    "Sign up": "サインアップ",
    "Sign up for a free Creative Cloud account to collaborate on the folder {0} and get 2GB of free cloud storage.": "無料の Creative Cloud アカウントにサインアップすると、フォルダー {0} を共有し、2 GB の無料クラウドストレージをご使用いただけます。",
    "Sign up is unavailable at this time. Please try again later.": "現在サインアップができません。後でもう一度試してください。",
    "Signing in...": "サインイン中...",
    "Single Edition allows a designer to use Adobe InDesign to build an iPad app with engaging elements such as slideshows, embedded audio and video, image pan, zoom and panoramas, 360-degree object rotation and more - all without writing code. Using only tools created by Adobe, you can create engaging apps with lots of interactivity. The apps built can be submitted and sold through the Apple App Store. Single Edition is now included as part of an Adobe Creative Cloud membership. The following instructions will help you get started!": "Single Edition を使用すると、デザイナーは Adobe InDesign を使用して iPad アプリケーションを作成することができます。スライドショー、オーディオやビデオの埋め込み、画像のパン、ズーム、パノラマ、さらに 360°回転するオブジェクトなど、すべての要素をコードを記述することなく活用できます。アドビのツールだけで、インタラクティビティを数多く備えた魅力的なアプリケーションを作成することができ、作成したアプリケーションは Apple App Store に送信して販売することも可能です。Single Edition は、Adobe Creative Cloud メンバーシップにも含まれています。次の説明を読んで、今すぐ使い始めましょう。",
    "Size": "サイズ",
    "Size copied to clipboard": "サイズをクリップボードにコピーしました",
    "Sorry, an error has occurred.": "エラーが発生しました。",
    "Sorry, but Behance requires images that are at least {0} pixels wide and {1} pixels tall.": "幅 {0} ピクセル、高さ {1} ピクセル未満の画像は Behance にアップロードできません。",
    "Sorry, but the following characters may not be used in file names: |, &quot;, ?, <, >, /, \\\\, :, *. {0}Learn More{1}.": "次の文字をファイル名に使うことはできません: |、&quot;、?、<、>、/、\\\\、:、*。{0}詳細情報{1}",
    "Sorry, the Collaboration feature is not yet available.": "コラボレーション機能はまだご利用いただけません。",
    "Sorry, this browser does not support that specific drag-and-drop behavior.": "このブラウザーはご指定のドラッグ＆ドロップ操作をサポートしていません。",
    "Sorry, this invitation has been accepted or revoked.": "この招待は既に承認済みであるか、取り消されました。",
    "Sorry, this link is no longer active.": "このリンクは有効ではありません。",
    "Sorry, this resource can not be publicly shared.": "このリソースは一般公開できません。",
    "Sorry, we're having some technical difficulties.": "申し訳ありません。技術的な問題が発生しています。",
    "Sorry, you are trying to view an invitation that no longer exists. This is most likely because you already accepted the invitation.": "既に存在しない招待を表示しようとしました。既にこの招待を承諾している可能性があります。",
    "Sorry, you are trying to view an invitation that was not sent to this account. Please log in using the email address to which the invitation was sent, or ask the person who invited you to resend the invitation to this account.": "このアカウントに送信されていない招待を表示しようとしました。招待の送信先の電子メールアドレスを使用してログインするか、招待主にこのアカウントに招待を再送するよう依頼してください。",
    "Sorry, you have exceeded your storage quota.": "割り当てられているストレージ容量を超過しました。",
    "Sort": "並べ換え",
    "Start and maintain your website online": "オンラインでの web サイトの公開および管理",
    "Still Having Trouble?": "引き続き問題が発生する場合",
    "Storage": "ストレージ",
    "Storage plans": "ストレージプラン",
    "Store your files in the cloud to access your creativity from any device.": "ファイルをクラウドに保存すれば、どのデバイスからでもアクセスして作業を行えます。",
    "Streamline your workflow with link sharing &amp; folder collaboration.": "リンクやフォルダーの共有により、ワークフローを効率化できます。",
    "Styles": "スタイル",
    "Sync From Your Desktop": "デスクトップから同期",
    "TB": "TB",
    "Team Management": "グループ管理",
    "Temporary Sites ({0})": "一時的なサイト ({0})",
    "Terms of Use": "利用条件",
    "Test": "テスト",
    "Text copied to clipboard": "クリップボードにテキストがコピーされました",
    "Thank you for signing up. Keep an eye on your email for an early access invitation!": "お申し込みありがとうございます。準備が整い次第、先行アクセスプログラムへの招待状を電子メールにてお送りします。",
    "Thank you for signing up. Keep an eye on your email for an invitation!": "お申し込みありがとうございます。準備が整い次第、電子メールにてご連絡差し上げます。",
    "Thank you for your patience.": "ご迷惑をおかけしますが、どうぞよろしくお願い申し上げます。",
    "Thank you! Please check your email for instructions on verifying your email address.": "ありがとうございました。電子メールアドレスの確認方法を記した電子メールを確認してください。",
    "Thank you, {0}.": "{0}様、ご利用いただきありがとうございます。",
    "Thanks for your patience!": "ご不便をおかけして申し訳ありません。",
    "The Adobe Application Manager lets you download every app available on Creative Cloud straight to your desktop.": "Adobe Application Manager を使用すれば、Creative Cloud で提供されているすべてのアプリケーションをデスクトップに直接ダウンロードできます。",
    "The Adobe ID and/or password provided does not appear to be valid. Please try again.": "指定した Adobe ID またはパスワードは有効ではないようです。もう一度実行してください。",
    "The Creative Cloud Download Center is currently unavailable.": "Creative Cloud ダウンロードセンターは現在利用できません。",
    "The archive is empty.": "アーカイブが空です。",
    "The early access program has concluded and Adobe has now made file sync available to all users.": "先行アクセスプログラムは終了し、すべてのユーザーがファイルの同期機能をご利用いただけるようになりました。",
    "The email address provided has either already been verified or did not match an account on file.": "指定した電子メールアドレスは既に確認されているか、ファイル上のアカウントと一致しませんでした。",
    "The maximum number of collaborators has been reached.": "共同利用者の最大数に達しました。",
    "The provided email address could not be matched to an account on file. Please try again.": "指定したメールアドレスはファイルのアカウントと一致しません。もう一度実行してください。",
    "The public url has been sent to {0}": "公開 URL を {0} に送信しました",
    "The verification email has been sent. Please check your inbox and click the link to verify.": "確認用電子メールが送信されました。受信ボックスを確認して、リンクをクリックして確認してください。",
    "The {0} name entered exceeds the 255 character limit and may have been truncated.": "入力した名前 {0} は文字数の上限 (255 文字) を超えているため、文字切れが発生している可能性があります。",
    "There are no comments for this item yet.": "このアイテムにはまだコメントがありません。",
    "There was a problem sharing your file. Please try again later.": "ファイルの共有で問題が発生しました。後でもう一度試してください。",
    "There was an error moving {0} items": "{0} 個の項目を移動するときにエラーが発生しました",
    "There was an error submitting your report, please try again": "レポートの送信中にエラーが発生しました。もう一度実行してください",
    "These people can view, edit, rename, move, or delete the contents of this Design Library. They can also invite or remove collaborators.": "共有者は、このデザインライブラリのコンテンツを表示、編集、名前変更、移動、削除することができます。また、他の共同作業者を招待したり、削除することもできます。",
    "These people can view, edit, rename, move, or delete the contents of this folder. They can also invite or remove collaborators.": "共有者は、このフォルダーのコンテンツを表示、編集、名前変更、移動、削除することができます。また、他の共同作業者を招待したり、削除することもできます。",
    "This action will remove your access to the selected shared folder(s). Other collaborators will still have access.": "この操作を行うと、選択した共有フォルダーにアクセスできなくなります。他の共有者は引き続きアクセスできます。",
    "This feature is not yet implemented": "この機能はまだ実装されていません",
    "This file is larger than the current version. You don't have enough space left to restore it. Please permanently delete other files to make room.": "このファイルは現行バージョンよりファイルサイズが大きいため、復元するための十分なスペースが不足しています。他のファイルを削除して、スペースを確保してください。",
    "This folder is empty": "このフォルダーは空です",
    "This folder is empty.": "このフォルダーは空です。",
    "This layer contains blend modes that may not be rendered correctly with the current combination of visible layers.": "このレイヤーには、現在表示されているレイヤーの組わせでは正しく表示されない描画モードが含まれています。",
    "This layer contains font substitutions so the font-size CSS reported is approximate.": "このレイヤーには代替フォントが含まれているため、CSS が表示するフォントサイズは概算値です。",
    "This page is taking too long to load.": "このページは読み込みに時間がかかりすぎます。",
    "This page is temporarily unavailable. We\\'ll be back soon.": "このページは一時的に利用できなくなっています。今しばらくお待ちください。",
    "This search did not return any results.": "検索条件に該当する項目はありません。",
    "This video introduces the general process of building your first folio, the content for your app. For additional tips and techniques, download Adobe\\'s free {0}DPS Tips{1} application from the Apple App Store and read the &quot;Single Edition&quot; issue.": "このビデオでは、初めてフォリオ (アプリケーションのコンテンツ) を作成する一般的な手順をご説明します。さらなるヒントや手法については、Apple App Store からアドビの無料アプリケーション {0}Digital Publishing Suite Tips{1} をダウンロードし、「Single Edition」の記事をお読みください。",
    "This video introduces the process involved in establishing an iOS developer membership with Apple. For detailed instructions, refer to the &quot;Enroll in Apple\\'s iOS Developer Program&quot; section in the Step-by-Step Guide.": "このビデオでは、Apple の iOS ディベロパーメンバーシップへの加入手順をご説明します。詳しくは、ステップバイステップガイドの「Apple iOS Developer Program への登録」をご覧ください。",
    "This video provides an overview of the tools used in the Single Edition workflow, terminology and requirements. Refer to the &quot;Introduction&quot; section in the Step-by-Step Guide.": "このビデオでは、Single Edition ワークフローで使用するツール、用語、および必要なアイテムの概要をご説明します。ステップバイステップガイドの「はじめに」をご覧ください。",
    "Tip: ": "説明 : ",
    "Title": "タイトル",
    "Title required": "タイトルを入力してください",
    "To access this site, please upgrade your browser. Read our {0}system requirements{1} for more information.": "このサイトにアクセスするには、ブラウザーをアップグレードしてください。詳しくは、{0}必要システム構成{1}をご覧ください。",
    "To free up space, try permanently deleting files": "空き領域を増やすには、ファイルを完全に削除してみてください",
    "To free up space, try permanently deleting files from your {0}.": "空き領域を増やすには、ファイルを {0} から完全に削除してみてください。",
    "To get below your limit, please permanently delete files": "制限を上回らないようにするには、ファイルを完全に削除してください",
    "To get started, install the free {0}desktop app{1}.": "開始するには、無料の{0}デスクトップアプリケーション{1}をインストールしてください。",
    "To get started, just install the free {0}Creative Cloud desktop app{1}. If you already have it installed, simply relaunch the app. Then, go to the Files panel to start syncing.": "使用を開始するには、無料の{0}Creative Cloud デスクトップアプリケーション{1}をインストールするだけです。既にインストールされている場合は、アプリケーションを起動し、ファイルパネルに移動して同期を開始します。",
    "To protect the security of your account, you must reset your password. Please check your inbox for an email we just sent you with instructions for how to reset your password and log into your account.": "アカウントのセキュリティを保持するために、パスワードの変更が必要です。パスワードを変更するための手順とアカウントへのログイン方法が記載されたメールを送信しましたのでご確認ください。",
    "To remove your settings files from Creative Cloud, click {0}Clear Settings{1} below.": "Creative Cloudから設定ファイルを削除するには、以下の{0}設定をクリア{1}をクリックしてください。",
    "To report a Copyright Violation, please follow Section 17 in the {0}Terms of Use{1}.": "著作権の侵害を報告するには、{0}利用条件{1}の第 17 条に従ってください。",
    "Today": "今日",
    "Toggle Measurement Tooltip": "計測ツールチップの表示切り替え",
    "Toggle Show Info on hover": "マウスポインターを合わせたときの情報表示を切り替え",
    "Toggles measurement tooltip on hover.": "ホバー時の計測ツールチップの表示を切り替えます。",
    "Trademark Infringement": "商標権の侵害",
    "Trouble signing in?": "サインインに問題がある場合",
    "Try Extract for PSD to web workflows": "Extract を使用して PSD ファイルを Web ワークフローに",
    "Try refreshing your browser or see our ": "ブラウザー画面をリフレッシュするか、または",
    "Type": "ファイル形式",
    "Uh oh, this PSD has an exceptional number of layers and has failed to process.": "この PSD には不正な数のレイヤーが含まれているため、処理できませんでした。",
    "Uh oh, this PSD has an exceptional number of layers and has failed to process. Please keep the number of layers below {0}. This PSD has {1}.": "この PSD には不正な数のレイヤーが含まれているため、処理できませんでした。レイヤーの数は {0} 以下にしてください。この PSD に含まれているレイヤー数は {1} です。",
    "Uh oh, this PSD was not successfully processed because it's not currently compatible with Extract.": "この PSD は現在 Extract との互換性がないため、正常に処理されませんでした。",
    "Unable to Connect to Behance": "Behance に接続できません",
    "Undo": "元に戻す",
    "Upgrade": "アップグレード",
    "Upload": "アップロード",
    "Upload Your Files": "ファイルをアップロード",
    "Upload a PSD": "PSD をアップロード",
    "Upload complete": "アップロード完了",
    "Upload failed: an item named {0} already exists.": "アップロードに失敗しました : アイテム {0} は既に存在します。",
    "Upload files": "ファイルをアップロード",
    "Uploaded": "アップロード日時",
    "Uploading .app archive files is not supported. Please try again with a different file type.": ".app アーカイブファイルのアップロードはサポートされていません。別のファイルタイプでもう一度お試しください。",
    "Uploading folders is not supported. Create a folder first, then drag your files into it.": "フォルダーのアップロードはサポートされていません。まずフォルダーを作成してから、ファイルをフォルダー内にドラッグしてください。",
    "Uploading this type of file or folder is not supported via drag-and-drop.": "この種類のファイルまたはフォルダーのドラッグ＆ドロップによるアップロードはサポートされていません。",
    "Uploading...": "アップロードしています...",
    "Use Extract for PSD to web workflows": "Web ワークフローに Extract for PSD を使用",
    "Use an existing Account": "既存のアカウントを使用",
    "Use as Cover": "表紙として使う",
    "Use shift-click to measure the distance between elements in the PSD view.": "Shift キーを押しながらクリックして、PSD ビューでエレメント間の距離を計測します。",
    "Use the arrow keys to traverse the layers in your design.": "矢印キーを使用してレイヤー間を移動します。",
    "Use the desktop application to find information about software updates, see release notes, connect with your creative community, and manage synced files": "デスクトップアプリケーションを使用すると、ソフトウェアのアップデートに関する情報の検索、リリースノートの確認、クリエイティブコミュニティへのアクセス、同期されたファイルの管理が行えます",
    "Use the desktop application to install the programs you need, find information about software updates, sync and share files, and connect with the rest of your team": "デスクトップアプリケーションを使用すると、必要なプログラムのインストール、ソフトウェアのアップデートに関する情報の検索、ファイルの同期と共有、チームの他のメンバーへのアクセスが行えます",
    "Use the {0}file chooser{1}{2} to upload files.": "{0}ファイル選択{1}{2}を使用してファイルをアップロードしてください。",
    "Use this folder": "このフォルダーを使用",
    "Useful CSS here": "役立つ CSS はこちら",
    "User Interfaces": "UI",
    "User profile is unavailable at this time. Please try again later.": "現在ユーザープロファイルを使用できません。後でもう一度試してください。",
    "Valid description required": "有効な説明が必要です",
    "Valid email required": "有効な電子メールが必要です",
    "Valid name required": "有効な名前が必要です",
    "Value copied to clipboard": "クリップボードにコピーされた値",
    "Vector Shapes": "ベクトルシェイプ",
    "Versions": "バージョン",
    "Video": "ビデオ",
    "Video 1: Workflow for Creative Cloud and Digital Publishing Suite Single Edition": "ビデオ 1 : Creative Cloud および Digital Publishing Suite Single Edition のワークフロー",
    "Video 2: Preparing for Single Edition": "ビデオ 2 : Single Edition の準備",
    "Video 2: Preparing to build your Single Edition app": "ビデオ 2 : Single Edition アプリケーションのビルドの準備",
    "Video 3: Creating your Single Edition folio": "ビデオ 3 : Single Edition Folio の作成",
    "Video 3: Creating your folio": "ビデオ 3 : Folio の作成",
    "Video 4: Building your Single Edition app": "ビデオ 4 : Single Edition アプリケーションのビルド",
    "Video 4: Building your app": "ビデオ 4 : アプリケーションのビルド",
    "Video 5: Submitting your Single Edition app": "ビデオ 5 : Single Edition アプリケーションの申請",
    "Video 5: Submitting your app": "ビデオ 5 : アプリケーションの送信",
    "View": "表示",
    "View Archive": "アーカイブを表示",
    "View archive": "アーカイブを表示",
    "View archived files": "アーカイブされたファイルを表示する",
    "View design library: {0}": "デザインライブラリを表示 : {0}",
    "View folder: {0}": "フォルダーを表示 : {0}",
    "View less": "一部を表示",
    "View more": "すべてを表示",
    "View overview topics and detailed instructions": "概要の内容と詳しい説明を表示する",
    "View publications created using Digital Publishing Suite": "Digital Publishing Suite を使用して作成した出版物を見る",
    "Warning: This layer contains an incompatible graphic option: blend mode": "警告 : このレイヤーには互換性のないグラフィックオプションが含まれます : 描画モード",
    "Watch instructional videos about digital publishing": "Digital Publishing に関する説明ビデオを見る",
    "Watch more videos": "もっとビデオを見る",
    "Watch more videos from our expert partners": "エキスパートパートナーによるビデオを見る",
    "We are performing planned maintenance on this page and will have it back up shortly. We apologize for any inconvenience. For updates on site maintenance, please visit our {2}status site{3}.": "このページはメンテナンス中です。まもなく復旧いたします。ご不便をおかけして申し訳ありません。サイトメンテナンスの最新情報については、{2}ステータスサイト{3}で状況をご確認ください。",
    "We can\\'t find the page you\\'re looking for. {0} View {1}your files{2} or browse {3}your apps and services{4}.": "お探しのページが見つかりません。{0} {1}ファイル{2}を表示するか、{3}アプリおよびサービス{4}を参照してください。",
    "We couldn't find your collaboration invitation, it may have already been accepted, expired, or revoked by the sender.": "ファイル共有の招待が見つかりませんでした。この招待は既に承認済みであるか、有効期限が切れている、または差出人によって取り消された可能性があります。",
    "We sent you an email": "電子メールを送信しました",
    "We use the standard W3C SVG format which is supported by all viewers.": "すべてのビューアーに対応する W3C SVG 標準フォーマット",
    "We were unable to create your folder. Please try again later.": "フォルダーを作成できませんでした。後でもう一度やり直してください。",
    "We were unable to send an email to {0}. Please try again later.": "{0} に電子メールを送信できませんでした。しばらく待ってからもう一度実行してください。",
    "We're sorry, but we can't complete this upload because it would exceed our limit for the maximum number of items in your account. Please empty your archive or delete some items and try again.": "アカウント内のアイテムの数が上限を超えるため、このアップロードを完了できません。アーカイブを空にするか、一部のアイテムを削除してから、もう一度実行してください。",
    "We're sorry, but you can't archive these items because your archive is too full. Please permanently delete some items in your archive and try again.": "アーカイブがいっぱいであるため、これらのアイテムをアーカイブできません。アーカイブ内の一部のアイテムを完全に削除してから、もう一度実行してください。",
    "We're sorry, but you can't archive this item because your archive is too full. Please permanently delete some items in your archive and try again.": "アーカイブがいっぱいであるため、このアイテムをアーカイブできません。アーカイブ内の一部のアイテムを完全に削除してから、もう一度実行してください。",
    "We're sorry, but you can't create a new folder because it would exceed our limit for the maximum number of items in your account. Please empty your archive or delete some items and try again.": "アカウント内のアイテムの数が上限を超えるため、新しいフォルダーを作成できません。アーカイブを空にするか、一部のアイテムを削除してから、もう一度実行してください。",
    "We're sorry, but you can't create a new folder because it would exceed our limit for the maximum number of nested subfolders. Please create your new folder in a different directory.": "階層構造になっているサブフォルダーの数が上限を超えるため、新しいフォルダーを作成できません。他のディレクトリに作成してください。",
    "We're sorry, but you can't move new items to this folder because it would exceed our limit for the maximum number of items per folder. Please delete some items and try again.": "フォルダーごとのアイテムの数が上限を超えるため、このフォルダーに新しいアイテムを移動できません。アーカイブを空にするか、一部のアイテムを削除してから、もう一度実行してください。",
    "We're sorry, but you can't move this folder because the destination folder has exceeded our limit for the maximum number of nested subfolders. Please move this folder to a different directory.": "移動先のフォルダーで階層構造になっているサブフォルダーの数が上限を超えているため、このフォルダーを移動できません。他のディレクトリに移動してください。",
    "We're sorry. You can't share this folder because at least one of its sub-folders has collaborators.{0} To share this folder, first remove all collaborators from its sub-folders, then re-invite everyone to this folder. When you add collaborators to a folder, its sub-folders are automatically shared with the same people.": "このフォルダーの少なくとも 1 つのサブフォルダーに共同利用者がいるため、このフォルダーを共有できません。{0} このフォルダーを共有するにはそのサブフォルダーからすべての共同利用者を削除して、全員を再度このフォルダーに招待してください。フォルダーに共同利用者を追加すると、サブフォルダーは自動的に同じ人と共有されます。",
    "We\\'re rolling out file sync in limited batches to Creative Cloud members. Sign up here to register for early access. We\\'ll add you to the waiting list, and send you an email once you\\'re in.": "ファイルの同期機能の提供は、現在一部の方に制限しており、今後数回にわたり Creative Cloud メンバーにアクセスを公開する予定です。先行アクセスプログラムにお申し込みいただくには、以下よりご登録をお願いします。お申し込み順にご案内する予定です。",
    "We\\'re sorry, this file cannot be shared due to the detection of copyrighted material. {0}Learn more{1}.": "申し訳ありません。著作権の設定されているアイテムが検出されたため、このファイルは共有できません。{0}詳細情報{1}。",
    "We\\'re sorry, this file type cannot be shared at this time. {0}Learn more{1}.": "申し訳ありません。現在、このファイル形式は共有できません。{0}詳細情報{1}。",
    "We\\'re sorry, we had trouble adding your comment. Please refresh the page and try again.": "申し訳ありません。コメントの追加中に問題が発生しました。ページを更新してからもう一度やり直してください。",
    "We\\'re sorry. Something seems to be wrong on our end. Please {0}try again{1} later. If this continues to fail, please contact {2}Customer Support{3}.": "申し訳ございません。弊社側で問題が発生した可能性があります。後で{0}やり直して{1}ください。引き続きエラーが発生する場合は、{2}カスタマーサポート{3}にお問い合わせください。",
    "We\\'re sorry. We have encountered an error while processing your cancellation. Please contact {0}Customer Support{1} to cancel your membership.": "解約処理中にエラーが発生しました。{0}カスタマーサポート{1}にご連絡いただき、メンバーシップを解約してください。",
    "We\\'re working quickly to resolve the issue and we apologize for the delay. If you have the Creative Cloud app already installed on your machine, you can try using it to access new downloads and updates. Otherwise, please check back or see our {0}status site{1} for updates.": "この問題の解決に向けて対応中です。お待たせしており申し訳ありません。Creative Cloud アプリケーションを既にインストールされている場合は、そちらを使用して新しいダウンロードとアップデートをお試しいただくことができます。後でまた確認するか、{0}ステータスサイト{1}で状況をご確認ください。",
    "We\\'re working quickly to resolve the issue and we\\'re sorry for the delay. Please check back or see our {0}status site{1} for updates. Also, help is available in the {2}Creative Cloud forums{3}.": "この問題の解決に向けて対応中です。お待たせしており申し訳ありません。後でまた確認するか、{0}ステータスサイト{1}で状況をご確認ください。また、{2}Creative Cloud フォーラム{3}でもヘルプ情報を利用できます。",
    "We\\'re working quickly to resolve the issue and we\\'re sorry for the delay. Please check back or see our {0}status site{1} for updates. Also, help is available in the {2}forums{3}.": "この問題の解決に向けて対応中です。お待たせしており申し訳ありません。後でまた確認するか、{0}ステータスサイト{1}で状況をご確認ください。また、{2}フォーラム{3}でもヘルプ情報を利用できます。",
    "We\\'re working to improve the overall performance of the Creative Cloud files experience. Your account will be accessible again shortly. Please check back in a few minutes.": "Creative Cloud ファイル機能の全体的なパフォーマンスを向上するために対応中です。お客様のアカウントはまもなくご利用いただけるようになります。数分後に再度お試しください。",
    "Website design without coding": "コードを書かずにウェブサイトをデザイン",
    "Website, app design, and coding": "Web サイト、アプリケーションデザインおよびコーディング",
    "Websites": "Web サイト",
    "Welcome to Creative Cloud": "Creative Cloud へようこそ",
    "Welcome to Creative Cloud Files": "Creative Cloud Files へようこそ",
    "What are you reporting?": "報告内容",
    "What is Adobe Digital Publishing Suite, Single Edition?": "Adobe Digital Publishing Suite, Single Edition の概要",
    "Why are you reporting this content?": "このコンテンツを報告する理由",
    "Width": "幅",
    "With Digital Publishing Suite, Single Edition, you can use familiar InDesign skills to create, develop, and deliver iPad apps like brochures, portfolios, yearbooks and annual reports&#8212;with engaging interactive elements such as slideshows, embedded audio and video, pan and zoom images, panoramas, 360-degree object rotation and more&#8212;without writing code. Single Edition is now included as part of Adobe Creative Cloud. With a Creative Cloud membership, you can build an unlimited number of iPad apps and submit to the Apple App Store. Follow these instructions to get started!": "Digital Publishing Suite Single Edition を使用して、使い慣れた InDesign の技術を利用し、カタログ、パンフレット、ポートフォリオ、年間報告などの iPad 用のアプリケーションを作成、開発および配布を行うことができます。また、スライドショー、オーディオやビデオの埋め込み、画像のパンとズーム、パノラマ、さらに 360°回転するオブジェクトなどのインタラクティブなコンテンツを、コードを記述することなく含めることができます。Adobe Creative Cloud メンバーシップをご利用の方は、Single Edition を使用して数に制限なく iPad アプリケーションを作成することができ、Apple App Storeに申請することができます。使い方について詳しくは、次の説明をご覧ください。",
    "Working...": "作業中...",
    "Yes": "はい",
    "Yesterday": "昨日",
    "You": "ユーザー",
    "You are not allowed to share this file.": "このファイルを共有することはできません。",
    "You can only replace this file with another {0} file.": "このファイルは {0} 形式ファイルでのみ置き換えることができます。",
    "You can select multiple layers in the Layers tab and export them as a single image.": "「レイヤー」タブで複数のレイヤーを選択して、単一の画像として書き出すことができます。",
    "You can\\'t upload new files while over your storage limit. Please permanently delete files from the Archive and try again.": "ストレージ容量の上限を超過しているため、新しいファイルをアップロードできません。ファイルをアーカイブから完全に削除して、もう一度実行してください。",
    "You currently do not have any synced settings.": "現在、同期された設定はありません。",
    "You done goofed.": "失敗しました。",
    "You have made too many failed Sign In attempts with this Adobe ID and we have temporarily locked this address. Please try again in a few minutes.": "この Adobe ID でのサインインの失敗が多すぎたので、このアドレスは一時的にロックされています。少し時間をおいてから再試行してください。",
    "You have no archived files.": "アーカイブされたファイルがありません。",
    "You have no more pending invitations": "保留中の他の招待状はありません",
    "You have no pending invitations.": "保留中の招待状はありません。",
    "You have restored to the version from {0}.": "{0}のバージョンに復元しました。",
    "You left the folder: {0}": "残したフォルダー : {0}",
    "You must {0}verify your email address{1} in order to make this file public by clicking the link provided in the verification email.": "このファイルを公開するには、{0}電子メールアドレスを確認{1}して、確認用電子メールに記載されたリンクをクリックする必要があります。",
    "You\\'re about to install the Adobe Application Manager": "Adobe Application Manager をインストールしようとしています",
    "You\\'re about to install {0}": "{0} のインストール手順",
    "You\\'re signed in using": "次の ID でサインイン中 :",
    "You\\'re {0} over your storage limit.": "ストレージ容量の上限を {0} 超過しています。",
    "Your Email": "電子メール",
    "Your Name": "名前",
    "Your account is undergoing routine maintenance.": "お客様のアカウントは定期メンテナンス中です。",
    "Your browser is no longer supported and you may have trouble using certain features. Please upgrade your browser. Read our {0}system requirements{1} for more information.": "お使いのブラウザーはサポートされなくなりました。特定の機能を使用する際に問題が発生する可能性があります。ブラウザーをアップグレードしてください。詳しくは、{0}必要システム構成{1}をご覧ください。",
    "Your browser is no longer supported.": "お使いのブラウザーはサポートされなくなりました。",
    "Your browser may ask you to accept the download": "ブラウザーからファイルの保存を確認された場合",
    "Your cloud storage is almost full.": "クラウドストレージが、もうすぐいっぱいになります。",
    "Your email address has not been verified. {0}Click here{1} to send an email with verification instructions.": "電子メールアドレスの確認が済んでいません。確認方法を記した電子メールを送信するには、{0}ここをクリック{1}してください。",
    "Your file has been shared with {0}": "ファイルは {0} と共有されました",
    "Your files are importing and will appear momentarily": "ファイルを読み込み中で、まもなく表示されます",
    "Your folder can not be created. Please remove any characters that are not letters or numbers and try again.": "フォルダーを作成できません。文字または数字以外の文字を削除し、もう一度やり直してください。",
    "Your folder name ends with a period (.) which is not allowed. Please remove the character or try another name.": "フォルダー名をピリオド (.) で終わることはできません。ピリオドを削除するか別の名前にしてください。",
    "Your payment has been processed.": "お支払いが処理されました。",
    "Your redemption code has been applied.": "引き換えコードが適用されました。",
    "Your report has been submitted": "レポートが送信されました",
    "Your search did not match any files": "検索条件に一致するファイルがありませんでした",
    "Your storage plan has been changed to {0}.{1}It may take a few minutes for you to see the update to your total storage.": "ストレージ容量が {0} に変更されました。{1}アップデートされた総ストレージ容量の確認には、少し時間がかかることがあります。",
    "Zoom": "ズーム",
    "Zoom in and out on your PSD view using ALT +/-.": "PSD ビューで ALT + プラス (+) / マイナス (-) キーをクリックして拡大・縮小します。",
    "Zoom preview canvas in and out.": "プレビューしているカンバスを拡大・縮小します。",
    "Zoom to 100%": "100% 表示",
    "Zoom to fit width in view": "画面に合わせて表示幅を拡大・縮小する",
    "already joined": "加入済み",
    "archive": "アーカイブ",
    "at {0}": "{0}",
    "back": "最背面へ",
    "by {0}": "作者 : {0}",
    "clear": "消去",
    "color swatch": "カラースウォッチ",
    "default": "初期設定",
    "file": "ファイル",
    "folder": "フォルダー",
    "for updates.": "で最新情報をご確認ください。",
    "here": "ここをクリックしてください",
    "invited again": "再度招待済み",
    "just now": "数秒前",
    "loading...": "読み込み中...",
    "no subfolders": "サブフォルダーなし",
    "of": "/",
    "or": "または",
    "original": "元の形式",
    "status page ": "ステータスページ",
    "submitted": "送信済み",
    "test": "テスト",
    "the provided email addresses": "指定された電子メールアドレス",
    "true": "true",
    "{0} B": "{0} B",
    "{0} file was too large and did not upload.": "{0} ファイルが大きすぎるため、アップロードされませんでした。",
    "{0} file was too large and did not upload. Please download {1} to sync files larger than {2}.": "{0} ファイルは大きすぎるため、アップロードできませんでした。{2} より大きいファイルの同期には、{1} をダウンロードしてください。",
    "{0} files were too large and did not upload.": "{0} ファイルが大きすぎるため、アップロードされませんでした。",
    "{0} files were too large and did not upload. Please download {1} to sync files larger than {2}.": "{0} ファイルは大きすぎるため、アップロードできませんでした。{2} より大きいファイルの同期には、{1} をダウンロードしてください。",
    "{0} has been deleted": "{0} を削除しました",
    "{0} has been restored": "{0} が復元されました",
    "{0} has invited you to the folder {1}. To view the folder, sign into Creative Cloud using your Adobe ID or create one now for free.": "{0} さんが、あなたをフォルダー「{1}」の共同作業者として招待しています。フォルダーを表示するには、お持ちの Adobe ID を使用するか、無料の Adobe ID を作成して、Creative Cloud にサインインしてください。",
    "{0} hour ago": "{0} 時間前",
    "{0} hours ago": "{0} 時間前",
    "{0} items have been deleted": "{0} 個のアイテムを削除しました",
    "{0} items have been restored": "{0} 個のアイテムを復元しました",
    "{0} minute ago": "{0} 分前",
    "{0} minutes ago": "{0} 分前",
    "{0} of {1}": "{0}/{1}",
    "{0} selected": "{0} 選択しました",
    "{0}-{1} of {2}": "{0}-{1} / {2}",
    "{0}B": "{0}B",
    "{0}Begin{1}{2} storing, sharing and collaborating on your work.": "作業の保存、共有、協力を{0}始めましょう{1}{2}。",
    "{0}GB": "{0} GB",
    "{0}Private{1}: Only you can view this {2}. Create a public link to share a read-only view of this {3} with others.": "{0}非公開{1} : 他の人はこの {2} を閲覧できません。この読み取り専用表示の {3} を他の人と共有するには、公開リンクを作成してください。",
    "{0}Public{1}: Anyone with the link can view this {2}. Remove the link to make the {3} private again.": "{0}公開{1} : この {2} を誰でも閲覧できます。{3} を再度非公開にするには、リンクを削除してください。",
    "{0}The Download Center{1} is still available to download apps.": "引き続き、{0}ダウンロード センター{1}からアプリケーションをダウンロードできます。",
    "{0}px": "{0} px"
});